# file: .github/actions/clean-build-folder/action.yml
name: Remove files not required for releases

runs:
  using: "composite"
  steps:
  - run: |
      ./prepareRelease.sh
      rm -rf $(find . -type d -name ".bmx")
      rm -rf $(find . -type d -name ".git")
      rm -rf $(find . -type d -name ".github")
      rm -rf $(find . -name ".gitignore")
      rm -rf $(find . -name ".gitattributes")
      rm -rf ".bmx_tmp_build"
      rm -f *.bmx
      rm -f *.bmk
      rm -rf "source"
      rm -rf "tests"
      rm -rf "tools"
      rm -rf "unittests"
      rm -rf "res/gfx/gui/flags/currently_unused"
      rm -rf "Misc/changeLogGenerator"
      rm -rf "Misc/compilerAddons"
      rm -rf "Misc/appData"
      rm -rf "Misc/music"
      rm -rf "Misc/documentation"
      rm -rf "Misc/sfx"
      rm -f savegames/*.*
      rm -f "config/settings.user.xml"
      rm -f "docs/Spielanleitung.CREATE.sh"
      rm -f log.*.txt
      rm -f "README.md"
      rm -f "TODO.txt"
      rm -f "TVTower.Profile.sh"
      rm -f "TVTower.profile.txt"
      rm -f "TVTower.Win32.c"
      rm -f "TVTower.desktop"
      rm -f "TVTower.debug.exe"
      rm -f "TVTower.debug"
      rm -f "TVTower.exe"
      rm -f "TVTower"
      rm -f "TVTower_DirectX7.bat"
      rm -f "prepareRelease.sh"
     
    shell: bash
