import brl.blitz
import brl.timer
import brl.graphics
import brl.maxlua
import brl.threads
import "bnetex.bmx"
import "basefunctions.bmx"
import "files.bmx"
import "basefunctions_guielements.bmx"
import "basefunctions_events.bmx"
import "basefunctions_deltatimer.bmx"
TPlayerProgrammePlan^brl.blitz.Object{
List:TObjectList&=mem:p("_bb_TPlayerProgrammePlan_List")
.ProgList:TObjectList&
.ContractList:TObjectList&
.NewsList:TObjectList&
-New%()="_bb_TPlayerProgrammePlan_New"
-ClearLists%()="_bb_TPlayerProgrammePlan_ClearLists"
+Create:TPlayerProgrammePlan()="_bb_TPlayerProgrammePlan_Create"
-ProgrammePlaceable%(Programme:TProgramme,time%=-1,day%=-1)="_bb_TPlayerProgrammePlan_ProgrammePlaceable"
-ContractPlaceable%(Contract:TContract,time%=-1,day%=-1)="_bb_TPlayerProgrammePlan_ContractPlaceable"
-GetActualProgramme:TProgramme(time%=-1,day%=-1)="_bb_TPlayerProgrammePlan_GetActualProgramme"
-GetActualContract:TContract(time%=-1,day%=-1)="_bb_TPlayerProgrammePlan_GetActualContract"
-GetActualAdBlock:TAdBlock(playerID%,time%=-1,day%=-1)="_bb_TPlayerProgrammePlan_GetActualAdBlock"
-GetActualNews:TNews(position%)="_bb_TPlayerProgrammePlan_GetActualNews"
-RefreshProgrammePlan%(playerID%,day%)="_bb_TPlayerProgrammePlan_RefreshProgrammePlan"
-RefreshAdPlan%(playerID%,day%)="_bb_TPlayerProgrammePlan_RefreshAdPlan"
-RefreshNewsPlan%(playerID%)="_bb_TPlayerProgrammePlan_RefreshNewsPlan"
-AddProgramme%(_Programme:TProgramme,takegivenDay@=0)="_bb_TPlayerProgrammePlan_AddProgramme"
-CloneProgramme:TProgramme(_Programme:TProgramme)="_bb_TPlayerProgrammePlan_CloneProgramme"
-RemoveProgramme%(_Programme:TProgramme)="_bb_TPlayerProgrammePlan_RemoveProgramme"
-RemoveAllProgrammeInstances%(_Programme:TProgramme,playerID%=0)="_bb_TPlayerProgrammePlan_RemoveAllProgrammeInstances"
-AddContract%(_Contract:TContract,owner%)="_bb_TPlayerProgrammePlan_AddContract"
-AddNews%(_News:TNews,owner%,sendposition%=0)="_bb_TPlayerProgrammePlan_AddNews"
-RemoveNews%(_news:TNews,owner%=0)="_bb_TPlayerProgrammePlan_RemoveNews"
+CloneNews:TNews(_news:TNews)="_bb_TPlayerProgrammePlan_CloneNews"
+CloneContract:TContract(_contract:TContract)="_bb_TPlayerProgrammePlan_CloneContract"
-RemoveContract%(_contract:TContract)="_bb_TPlayerProgrammePlan_RemoveContract"
-GetPreviousContractCount%(_contract:TContract)="_bb_TPlayerProgrammePlan_GetPreviousContractCount"
-RenewContractCount%(_contract:TContract)="_bb_TPlayerProgrammePlan_RenewContractCount"
-DebugAll%()="_bb_TPlayerProgrammePlan_DebugAll"
}="bb_TPlayerProgrammePlan"
TPlayerProgrammeCollection^brl.blitz.Object{
.List:brl.linkedlist.TList&
.NewsList:brl.linkedlist.TList&
.MovieList:brl.linkedlist.TList&
.SeriesList:brl.linkedlist.TList&
.ContractList:brl.linkedlist.TList&
-New%()="_bb_TPlayerProgrammeCollection_New"
-ClearLists%()="_bb_TPlayerProgrammeCollection_ClearLists"
-GetOriginalProgramme:TProgramme(_programme:TProgramme)="_bb_TPlayerProgrammeCollection_GetOriginalProgramme"
-TopicalityToProgrammeClones%(_programme:TProgramme,_list:TObjectList)="_bb_TPlayerProgrammeCollection_TopicalityToProgrammeClones"
-RemoveOriginalContract%(_contract:TContract)="_bb_TPlayerProgrammeCollection_RemoveOriginalContract"
-AddNews%(news:TNews,owner%=0)="_bb_TPlayerProgrammeCollection_AddNews"
-RemoveProgramme%(programme:TProgramme,owner%=0)="_bb_TPlayerProgrammeCollection_RemoveProgramme"
-AddMovie%(movie:TProgramme,owner%=0)="_bb_TPlayerProgrammeCollection_AddMovie"
-AddContract%(contract:TContract,owner%=0)="_bb_TPlayerProgrammeCollection_AddContract"
-AddProgramme%(programme:TProgramme,owner%=0)="_bb_TPlayerProgrammeCollection_AddProgramme"
-AddSerie%(serie:TProgramme,owner%=0)="_bb_TPlayerProgrammeCollection_AddSerie"
-GetLocalRandomMovie:TProgramme()="_bb_TPlayerProgrammeCollection_GetLocalRandomMovie"
-GetLocalRandomSerie:TProgramme()="_bb_TPlayerProgrammeCollection_GetLocalRandomSerie"
-GetLocalRandomContract:TContract()="_bb_TPlayerProgrammeCollection_GetLocalRandomContract"
-GetProgramme:TProgramme(number%)="_bb_TPlayerProgrammeCollection_GetProgramme"
-GetContract:TContract(number%)="_bb_TPlayerProgrammeCollection_GetContract"
-GetMovieFromCollection:TProgramme(number%)="_bb_TPlayerProgrammeCollection_GetMovieFromCollection"
-GetSeriesFromCollection:TProgramme(number%)="_bb_TPlayerProgrammeCollection_GetSeriesFromCollection"
}="bb_TPlayerProgrammeCollection"
TContract^brl.blitz.Object{
List:brl.linkedlist.TList&=mem:p("_bb_TContract_List")
MinAudienceMultiplicator!&=mem:d("_bb_TContract_MinAudienceMultiplicator")
.title$&
.description$&
.daystofinish%&
.spotcount%&
.spotssent%&
.spotnumber%&
.botched%&
.senddate%&
.sendtime%&
.targetgroup%&
.minaudience%&
.profit%&
.finished%&
.clone%&
.penalty%&
.owner%&
.daysigned%&
.calculatedProfit%&
.calculatedPenalty%&
.calculatedMinAudience%&
.id%&
-New%()="_bb_TContract_New"
+Load:TContract(pnode:xmlNode)="_bb_TContract_Load"
+LoadAll%()="_bb_TContract_LoadAll"
+SaveAll%()="_bb_TContract_SaveAll"
-Save%()="_bb_TContract_Save"
+Create:TContract(title$,description$,daystofinish%,spotcount%,targetgroup%,minaudience%,profit%,penalty%,id%=0,owner%=0)="_bb_TContract_Create"
+CalculateMinAudienceMultiplicator%()="_bb_TContract_CalculateMinAudienceMultiplicator"
+GetRandomContract:TContract()="_bb_TContract_GetRandomContract"
+GetMinAudiencePercentage#(dbvalue%)="_bb_TContract_GetMinAudiencePercentage"
-CalculatePrice#(baseprice%=0)="_bb_TContract_CalculatePrice"
-CalculateMinAudience#()="_bb_TContract_CalculateMinAudience"
-GetMinAudienceNumber#(dbvalue%)="_bb_TContract_GetMinAudienceNumber"
+GetTargetgroupName$(group%)="_bb_TContract_GetTargetgroupName"
-getDaysToFinish%()="_bb_TContract_getDaysToFinish"
-ShowSheet%(x%,y%,plannerday%=-1)="_bb_TContract_ShowSheet"
+GetContract:TContract(number%)="_bb_TContract_GetContract"
}="bb_TContract"
TProgramme^brl.blitz.Object{
ProgList:brl.linkedlist.TList&=mem:p("_bb_TProgramme_ProgList")
ProgMovieList:brl.linkedlist.TList&=mem:p("_bb_TProgramme_ProgMovieList")
ProgSeriesList:brl.linkedlist.TList&=mem:p("_bb_TProgramme_ProgSeriesList")
.clone%&
.title$&
.description$&
.actors$&
.director$&
.country$&
.year%&
.livehour%&
.Outcome#&
.review#&
.speed#&
.relPrice%&
.Genre%&
.episodecount%&
.blocks%&
.fsk18$&
.isMovie%&
.episodeNumber%&
.topicality%&
.maxtopicality%&
.pid%&
.episodeList:brl.linkedlist.TList&
.used%&
.senddate%&
.sendtime%&
-New%()="_bb_TProgramme_New"
+Load:TProgramme(pnode:xmlNode,isEpisode%=0,origowner%=0)="_bb_TProgramme_Load"
+LoadAll%()="_bb_TProgramme_LoadAll"
+SaveAll%()="_bb_TProgramme_SaveAll"
-Save%(isepisode%=0)="_bb_TProgramme_Save"
-Buy%()="_bb_TProgramme_Buy"
-Sell%()="_bb_TProgramme_Sell"
+CountGenre%(Genre%,Liste:brl.linkedlist.TList)="_bb_TProgramme_CountGenre"
+GetProgramme:TProgramme(number%)="_bb_TProgramme_GetProgramme"
+GetMovie:TProgramme(number%)="_bb_TProgramme_GetMovie"
+GetEpisode:TProgramme(parentprogramme:TProgramme,number%)="_bb_TProgramme_GetEpisode"
+GetSeries:TProgramme(number%)="_bb_TProgramme_GetSeries"
+GetRandomMovie:TProgramme(playerID%=-1)="_bb_TProgramme_GetRandomMovie"
+GetRandomMovieWithMinPrice:TProgramme(MinPrice%,playerID%=-1)="_bb_TProgramme_GetRandomMovieWithMinPrice"
+GetRandomMovieWithBlocks:TProgramme(playerID%=-1,blocks%=0)="_bb_TProgramme_GetRandomMovieWithBlocks"
+GetRandomSerie:TProgramme(playerID%=-1)="_bb_TProgramme_GetRandomSerie"
+GetGenre$(Genre%)="_bb_TProgramme_GetGenre"
-ComputeTopicality#()="_bb_TProgramme_ComputeTopicality"
-ComputeAudienceQuote#(lastquote#=0#)="_bb_TProgramme_ComputeAudienceQuote"
-RefreshTopicality%()="_bb_TProgramme_RefreshTopicality"
-ComputePrice%()="_bb_TProgramme_ComputePrice"
-ShowSheet%(x%,y%,plannerday%=-1)="_bb_TProgramme_ShowSheet"
-ShowEpisodeSheet%(x%,y%,series:TProgramme)="_bb_TProgramme_ShowEpisodeSheet"
}="bb_TProgramme"
TNews^brl.blitz.Object{
LastUniqueID%&=mem("_bb_TNews_LastUniqueID")
List:brl.linkedlist.TList&=mem:p("_bb_TNews_List")
NewsList:brl.linkedlist.TList&=mem:p("_bb_TNews_NewsList")
.title$&
.description$&
.Genre%&
.quality%&
.price%&
.episodecount%&
.episode%&
.maxepisodes%&
.id%&
.episodeList:brl.linkedlist.TList&
.happenedday%&
.happenedhour%&
.happenedminute%&
.parentNews:TNews&
.sendposition%&
.owner%&
.used%&
-New%()="_bb_TNews_New"
+Load:TNews(pnode:xmlNode,isEpisode%=0,origowner%=0)="_bb_TNews_Load"
+LoadAll%()="_bb_TNews_LoadAll"
+SaveAll%()="_bb_TNews_SaveAll"
-Save%(isEpisode%=0)="_bb_TNews_Save"
+CountGenre%(Genre%,Liste:brl.linkedlist.TList)="_bb_TNews_CountGenre"
+GetRandomNews:TNews()="_bb_TNews_GetRandomNews"
+GetGenre$(Genre%)="_bb_TNews_GetGenre"
-ComputeTopicality#()="_bb_TNews_ComputeTopicality"
-ComputeAudienceQuote#(lastquote#=0#)="_bb_TNews_ComputeAudienceQuote"
-ComputePrice%()="_bb_TNews_ComputePrice"
+Create:TNews(title$,description$,Genre%,episode%=0,quality%=0,price%=0,id%=0)="_bb_TNews_Create"
-AddEpisode:TNews(title$,description$,Genre%,episode%=0,quality%=0,price%=0,id%=0)="_bb_TNews_AddEpisode"
+GetLast:TNews()="_bb_TNews_GetLast"
+GetRandomChainParent:TNews(Genre%=-1)="_bb_TNews_GetRandomChainParent"
+GetNextInNewsChain:TNews(currentNews:TNews,isParent%=0)="_bb_TNews_GetNextInNewsChain"
+GetNews:TNews(number%)="_bb_TNews_GetNews"
+GetASingleNews:TNews(Genre%=-1)="_bb_TNews_GetASingleNews"
}="bb_TNews"
TMovie^TProgramme{
LastUniqueID%&=mem("_bb_TMovie_LastUniqueID")
-New%()="_bb_TMovie_New"
+Create:TMovie(title$,description$,actors$,director$,country$,year%,livehour%,Outcome#,review#,speed#,relPrice%,Genre%,blocks%,fsk18$,id%=0,Own%=0)="_bb_TMovie_Create"
}="bb_TMovie"
TSeries^TProgramme{
LastUniqueID%&=mem("_bb_TSeries_LastUniqueID")
-New%()="_bb_TSeries_New"
+Create:TSeries(title$,description$,actors$,director$,country$,year%,livehour%,Outcome#,review#,speed#,relPrice%,Genre%,blocks%,fsk18$,episode%=0,id%=0,Own%=0)="_bb_TSeries_Create"
-AddEpisode:TSeries(title$,description$,actors$,director$,country$,year%,livehour%,Outcome#,review#,speed#,relPrice%,Genre%,blocks%,fsk18$,episode%=0,id%=0,Own%=0)="_bb_TSeries_AddEpisode"
+GetLast:TSeries()="_bb_TSeries_GetLast"
}="bb_TSeries"
TDatabase^brl.blitz.Object{
.file$&
.moviescount%&
.totalmoviescount%&
.seriescount%&
.newscount%&
.totalnewscount%&
.contractscount%&
-New%()="_bb_TDatabase_New"
+Create:TDatabase()="_bb_TDatabase_Create"
+Load%(filename$)="_bb_TDatabase_Load"
}="bb_TDatabase"
TAdBlock^TBlock{
LastUniqueID%&=mem("_bb_TAdBlock_LastUniqueID")
DragAndDropList:brl.linkedlist.TList&=mem:p("_bb_TAdBlock_DragAndDropList")
List:brl.linkedlist.TList&=mem:p("_bb_TAdBlock_List")
AdditionallyDragged%&=mem("_bb_TAdBlock_AdditionallyDragged")
MinutesHinweis%&=mem("_bb_TAdBlock_MinutesHinweis")
.title$&
.State%&
.timeset%&
.Height%&
.width%&
.botched%&
.blocks%&
.senddate%&
.sendtime%&
.contract:TContract&
.image:TGW_Sprites&
.image_dragged:TGW_Sprites&
.uniqueID%&
.Link:brl.linkedlist.TLink&
-New%()="_bb_TAdBlock_New"
+LoadAll%(loadfile:brl.stream.TStream)="_bb_TAdBlock_LoadAll"
+SaveAll%()="_bb_TAdBlock_SaveAll"
-Save%()="_bb_TAdBlock_Save"
+Create:TAdBlock(text$=$"unknown",x%=0,y%=0,owner%=0,contractpos%=-1)="_bb_TAdBlock_Create"
+CreateDragged:TAdBlock(contract:TContract,owner%=-1)="_bb_TAdBlock_CreateDragged"
+GetActualAdBlock:TAdBlock(playerID%=-1,time%=-1,day%=-1)="_bb_TAdBlock_GetActualAdBlock"
-SetDragable%(_dragable%=1)="_bb_TAdBlock_SetDragable"
-Compare%(otherObject:Object)="_bb_TAdBlock_Compare"
-GetBlockX%(time%)="_bb_TAdBlock_GetBlockX"
-GetBlockY%(time%)="_bb_TAdBlock_GetBlockY"
-GetTimeOfBlock%(_x%=1000,_y%=1000)="_bb_TAdBlock_GetTimeOfBlock"
-Draw%()="_bb_TAdBlock_Draw"
+DrawAll%(origowner%)="_bb_TAdBlock_DrawAll"
+UpdateAll%(origowner%)="_bb_TAdBlock_UpdateAll"
-RemoveOverheadAdblocks%()="_bb_TAdBlock_RemoveOverheadAdblocks"
+RemoveAdblocks%(Contract:TContract,BeginDay%=0)="_bb_TAdBlock_RemoveAdblocks"
-ShowSheet%(x%,y%)="_bb_TAdBlock_ShowSheet"
-GetPreviousContractCount%()="_bb_TAdBlock_GetPreviousContractCount"
-GetSuccessfullSentContractCount%()="_bb_TAdBlock_GetSuccessfullSentContractCount"
-RemoveBlock%()="_bb_TAdBlock_RemoveBlock"
-AddBlock%()="_bb_TAdBlock_AddBlock"
+GetBlockByContract:TAdBlock(contract:TContract)="_bb_TAdBlock_GetBlockByContract"
+GetBlock:TAdBlock(id%)="_bb_TAdBlock_GetBlock"
}="bb_TAdBlock"
TProgrammeBlock^TBlock{
LastUniqueID%&=mem("_bb_TProgrammeBlock_LastUniqueID")
DragAndDropList:brl.linkedlist.TList&=mem:p("_bb_TProgrammeBlock_DragAndDropList")
List:brl.linkedlist.TList&=mem:p("_bb_TProgrammeBlock_List")
AdditionallyDragged%&=mem("_bb_TProgrammeBlock_AdditionallyDragged")
.pbid%&
.id%&
.title$&
.Genre$&
.State%&
.timeset%&
.blocks%&
.blocktime%&[]&
.image:TGW_Sprites&
.image_dragged:TGW_Sprites&
.Programme:TProgramme&
.ParentProgramme:TProgramme&
.uniqueID%&
.Link:brl.linkedlist.TLink&
-New%()="_bb_TProgrammeBlock_New"
+LoadAll%(loadfile:brl.stream.TStream)="_bb_TProgrammeBlock_LoadAll"
+SaveAll%()="_bb_TProgrammeBlock_SaveAll"
-Save%()="_bb_TProgrammeBlock_Save"
-SetStartConfig%(x#,y#,owner%=0,state%=0)="_bb_TProgrammeBlock_SetStartConfig"
+Create:TProgrammeBlock(text$=$"unknown",x%=0,y%=0,serie%=0,owner%=0,programmepos%=-1)="_bb_TProgrammeBlock_Create"
+GetBlock:TProgrammeBlock(id%)="_bb_TProgrammeBlock_GetBlock"
+GetActualProgrammeBlock:TProgrammeBlock(playerID%=-1,time%=-1,day%=-1)="_bb_TProgrammeBlock_GetActualProgrammeBlock"
+CreateDragged:TProgrammeBlock(movie:TProgramme,parentMovie:TProgramme="bbNullObject",owner%=-1)="_bb_TProgrammeBlock_CreateDragged"
-SetDragable%(_dragable%=1)="_bb_TProgrammeBlock_SetDragable"
-Compare%(otherObject:Object)="_bb_TProgrammeBlock_Compare"
-GetTimeOfBlock%(extx%=-1,exty%=-1)="_bb_TProgrammeBlock_GetTimeOfBlock"
-GetEndTimeOfBlock%(extx%=-1,exty%=-1,extblocks%=-1)="_bb_TProgrammeBlock_GetEndTimeOfBlock"
-DraggingAllowed@()="_bb_TProgrammeBlock_DraggingAllowed"
-DrawBlockPart%(x%,y%,kind%)="_bb_TProgrammeBlock_DrawBlockPart"
+DrawAllShades%()="_bb_TProgrammeBlock_DrawAllShades"
-GetState%()="_bb_TProgrammeBlock_GetState"
-Draw%()="_bb_TProgrammeBlock_Draw"
-DeleteBlock%()="_bb_TProgrammeBlock_DeleteBlock"
-GetBlockX%(time%)="_bb_TProgrammeBlock_GetBlockX"
-GetBlockY%(time%)="_bb_TProgrammeBlock_GetBlockY"
-DragBlock%()="_bb_TProgrammeBlock_DragBlock"
-DropBlock%()="_bb_TProgrammeBlock_DropBlock"
+DrawAll%(origowner%=0)="_bb_TProgrammeBlock_DrawAll"
+UpdateAll%(origowner%=0)="_bb_TProgrammeBlock_UpdateAll"
}="bb_TProgrammeBlock"
TNewsBlock^TBlock{
LastUniqueID%&=mem("_bb_TNewsBlock_LastUniqueID")
DragAndDropList:brl.linkedlist.TList&=mem:p("_bb_TNewsBlock_DragAndDropList")
List:brl.linkedlist.TList&=mem:p("_bb_TNewsBlock_List")
AdditionallyDragged%&=mem("_bb_TNewsBlock_AdditionallyDragged")
LeftListPosition%&=mem("_bb_TNewsBlock_LeftListPosition")
LeftListPositionMax%&=mem("_bb_TNewsBlock_LeftListPositionMax")
.title$&
.State%&
.sendslot%&
.publishdelay%&
.publishtime%&
.paid@&
.news:TNews&
.image:brl.max2d.TImage&
.image_dragged:brl.max2d.TImage&
.uniqueID%&
.Link:brl.linkedlist.TLink&
-New%()="_bb_TNewsBlock_New"
+LoadAll%(loadfile:brl.stream.TStream)="_bb_TNewsBlock_LoadAll"
+SaveAll%()="_bb_TNewsBlock_SaveAll"
-Save%()="_bb_TNewsBlock_Save"
+Create:TNewsBlock(text$=$"unknown",x%=0,y%=0,owner%=1,publishdelay%=0,usenews:TNews="bbNullObject")="_bb_TNewsBlock_Create"
-Pay%()="_bb_TNewsBlock_Pay"
+IncLeftListPosition%(amount%=1)="_bb_TNewsBlock_IncLeftListPosition"
+DecLeftListPosition%(amount%=1)="_bb_TNewsBlock_DecLeftListPosition"
-SetDragable%(_dragable%=1)="_bb_TNewsBlock_SetDragable"
-Compare%(otherObject:Object)="_bb_TNewsBlock_Compare"
-GetSlotOfBlock%()="_bb_TNewsBlock_GetSlotOfBlock"
+GetBlock:TNewsBlock(id%)="_bb_TNewsBlock_GetBlock"
-Draw%()="_bb_TNewsBlock_Draw"
+DrawAll%(origowner%)="_bb_TNewsBlock_DrawAll"
+UpdateAll%(origowner%)="_bb_TNewsBlock_UpdateAll"
}="bb_TNewsBlock"
TContractBlocks^TBlock{
DragAndDropList:brl.linkedlist.TList&=mem:p("_bb_TContractBlocks_DragAndDropList")
List:brl.linkedlist.TList&=mem:p("_bb_TContractBlocks_List")
AdditionallyDragged%&=mem("_bb_TContractBlocks_AdditionallyDragged")
.image:TGW_Sprites&
.image_dragged:TGW_Sprites&
.contract:TContract&
.slot%&
.Link:brl.linkedlist.TLink&
-New%()="_bb_TContractBlocks_New"
+LoadAll%(loadfile:brl.stream.TStream)="_bb_TContractBlocks_LoadAll"
+SaveAll%()="_bb_TContractBlocks_SaveAll"
-Save%()="_bb_TContractBlocks_Save"
+ContractsToPlayer%(playerID%)="_bb_TContractBlocks_ContractsToPlayer"
+RemoveContractFromSuitcase%(contract:TContract)="_bb_TContractBlocks_RemoveContractFromSuitcase"
+Create:TContractBlocks(contract:TContract,slot%=0,owner%=0)="_bb_TContractBlocks_Create"
-SetDragable%(_dragable%=1)="_bb_TContractBlocks_SetDragable"
-Compare%(otherObject:Object)="_bb_TContractBlocks_Compare"
-Draw%()="_bb_TContractBlocks_Draw"
+DrawAll%(DraggingAllowed@)="_bb_TContractBlocks_DrawAll"
+UpdateAll%(DraggingAllowed@)="_bb_TContractBlocks_UpdateAll"
}="bb_TContractBlocks"
TMovieAgencyBlocks^TBlock{
DragAndDropList:brl.linkedlist.TList&=mem:p("_bb_TMovieAgencyBlocks_DragAndDropList")
List:brl.linkedlist.TList&=mem:p("_bb_TMovieAgencyBlocks_List")
AdditionallyDragged%&=mem("_bb_TMovieAgencyBlocks_AdditionallyDragged")
DebugMode@&=mem:b("_bb_TMovieAgencyBlocks_DebugMode")
HoldingType@&=mem:b("_bb_TMovieAgencyBlocks_HoldingType")
.image:brl.max2d.TImage&
.image_dragged:brl.max2d.TImage&
.Programme:TProgramme&
.slot%&
.Link:brl.linkedlist.TLink&
-New%()="_bb_TMovieAgencyBlocks_New"
+LoadAll%(loadfile:brl.stream.TStream)="_bb_TMovieAgencyBlocks_LoadAll"
+SaveAll%()="_bb_TMovieAgencyBlocks_SaveAll"
-Save%()="_bb_TMovieAgencyBlocks_Save"
-Buy%(PlayerID%=-1)="_bb_TMovieAgencyBlocks_Buy"
-Sell%(bymakler@=0,PlayerID%=-1)="_bb_TMovieAgencyBlocks_Sell"
+RemoveBlockByProgramme%(programme:TProgramme,playerID%=0)="_bb_TMovieAgencyBlocks_RemoveBlockByProgramme"
+ReFillBlocks%()="_bb_TMovieAgencyBlocks_ReFillBlocks"
+ProgrammeToPlayer%(playerID%)="_bb_TMovieAgencyBlocks_ProgrammeToPlayer"
+Create:TMovieAgencyBlocks(Programme:TProgramme,slot%=0,owner%=0)="_bb_TMovieAgencyBlocks_Create"
-SetDragable%(_dragable%=1)="_bb_TMovieAgencyBlocks_SetDragable"
-Compare%(otherObject:Object)="_bb_TMovieAgencyBlocks_Compare"
-GetSlotOfBlock%()="_bb_TMovieAgencyBlocks_GetSlotOfBlock"
-Draw%()="_bb_TMovieAgencyBlocks_Draw"
+DrawAll%(DraggingAllowed@)="_bb_TMovieAgencyBlocks_DrawAll"
+UpdateAll%(DraggingAllowed@)="_bb_TMovieAgencyBlocks_UpdateAll"
}="bb_TMovieAgencyBlocks"
TArchiveProgrammeBlocks^TBlock{
LastUniqueID%&=mem("_bb_TArchiveProgrammeBlocks_LastUniqueID")
DragAndDropList:brl.linkedlist.TList&=mem:p("_bb_TArchiveProgrammeBlocks_DragAndDropList")
List:brl.linkedlist.TList&=mem:p("_bb_TArchiveProgrammeBlocks_List")
AdditionallyDragged%&=mem("_bb_TArchiveProgrammeBlocks_AdditionallyDragged")
.Programme:TProgramme&
.slot%&
.alreadyInSuitcase@&
.owner%&
.uniqueID%&
.Link:brl.linkedlist.TLink&
-New%()="_bb_TArchiveProgrammeBlocks_New"
+LoadAll%(loadfile:brl.stream.TStream)="_bb_TArchiveProgrammeBlocks_LoadAll"
+SaveAll%()="_bb_TArchiveProgrammeBlocks_SaveAll"
-Save%()="_bb_TArchiveProgrammeBlocks_Save"
+ProgrammeToSuitcase%(playerID%)="_bb_TArchiveProgrammeBlocks_ProgrammeToSuitcase"
+ClearSuitcase%(playerID%)="_bb_TArchiveProgrammeBlocks_ClearSuitcase"
-ReAddProgramme%(playerID%)="_bb_TArchiveProgrammeBlocks_ReAddProgramme"
-RemoveProgramme%(programme:TProgramme,owner%=0)="_bb_TArchiveProgrammeBlocks_RemoveProgramme"
+Create:TArchiveProgrammeBlocks(Programme:TProgramme,slot%=0,owner%=0)="_bb_TArchiveProgrammeBlocks_Create"
+CreateDragged:TArchiveProgrammeBlocks(movie:TProgramme,owner%=-1)="_bb_TArchiveProgrammeBlocks_CreateDragged"
-Compare%(otherObject:Object)="_bb_TArchiveProgrammeBlocks_Compare"
-GetSlotOfBlock%()="_bb_TArchiveProgrammeBlocks_GetSlotOfBlock"
-Draw%()="_bb_TArchiveProgrammeBlocks_Draw"
+DrawAll%(DraggingAllowed@)="_bb_TArchiveProgrammeBlocks_DrawAll"
+UpdateAll%(DraggingAllowed@)="_bb_TArchiveProgrammeBlocks_UpdateAll"
}="bb_TArchiveProgrammeBlocks"
TAuctionProgrammeBlocks^brl.blitz.Object{
LastUniqueID%&=mem("_bb_TAuctionProgrammeBlocks_LastUniqueID")
List:brl.linkedlist.TList&=mem:p("_bb_TAuctionProgrammeBlocks_List")
DrawnFirstTime@&=mem:b("_bb_TAuctionProgrammeBlocks_DrawnFirstTime")
.x%&
.y%&
.imageWithText:brl.max2d.TImage&
.image:brl.max2d.TImage&
.Programme:TProgramme&
.height%&
.width%&
.slot%&
.Bid%&[]&
.uniqueID%&
.Link:brl.linkedlist.TLink&
-New%()="_bb_TAuctionProgrammeBlocks_New"
+ProgrammeToPlayer%()="_bb_TAuctionProgrammeBlocks_ProgrammeToPlayer"
+LoadAll%(loadfile:brl.stream.TStream)="_bb_TAuctionProgrammeBlocks_LoadAll"
+SaveAll%()="_bb_TAuctionProgrammeBlocks_SaveAll"
-Save%()="_bb_TAuctionProgrammeBlocks_Save"
+Create:TAuctionProgrammeBlocks(Programme:TProgramme,slot%=0)="_bb_TAuctionProgrammeBlocks_Create"
-Compare%(otherObject:Object)="_bb_TAuctionProgrammeBlocks_Compare"
-Draw%()="_bb_TAuctionProgrammeBlocks_Draw"
+DrawAll%(DraggingAllowed@)="_bb_TAuctionProgrammeBlocks_DrawAll"
-SetBid%(playerID%,price%)="_bb_TAuctionProgrammeBlocks_SetBid"
+UpdateAll%(DraggingAllowed@)="_bb_TAuctionProgrammeBlocks_UpdateAll"
}="bb_TAuctionProgrammeBlocks"
TPlannerList^brl.blitz.Object{
.openState%&
.currentGenre%&
.enabled%&
.Pos:TPosition&
-New%()="_bb_TPlannerList_New"
-GetOpen%()="_bb_TPlannerList_GetOpen"
}="bb_TPlannerList"
TgfxProgrammelist^TPlannerList{
.gfxgenres:TGW_Sprites&
.gfxmovies:TGW_Sprites&
.gfxtape:TGW_Sprites&
.gfxtapeseries:TGW_Sprites&
.gfxtapeepisodes:TGW_Sprites&
.gfxepisodes:TGW_Sprites&
.currentseries:TProgramme&
-New%()="_bb_TgfxProgrammelist_New"
+Create:TgfxProgrammelist(x%,y%)="_bb_TgfxProgrammelist_Create"
-Draw%(createProgrammeblock%=1)="_bb_TgfxProgrammelist_Draw"
-DrawTapes%(genre%,createProgrammeblock%=1)="_bb_TgfxProgrammelist_DrawTapes"
-UpdateTapes%(genre%,createProgrammeblock%=1)="_bb_TgfxProgrammelist_UpdateTapes"
-DrawEpisodeTapes%(series:TProgramme,createProgrammeblock%=1)="_bb_TgfxProgrammelist_DrawEpisodeTapes"
-UpdateEpisodeTapes%(series:TProgramme,createProgrammeblock%=1)="_bb_TgfxProgrammelist_UpdateEpisodeTapes"
-Update%(createProgrammeblock%=1)="_bb_TgfxProgrammelist_Update"
-SetOpen%(newState%)="_bb_TgfxProgrammelist_SetOpen"
}="bb_TgfxProgrammelist"
TgfxContractlist^TPlannerList{
.gfxcontracts:TGW_Sprites&
.gfxtape:TGW_Sprites&
-New%()="_bb_TgfxContractlist_New"
+Create:TgfxContractlist(x%,y%)="_bb_TgfxContractlist_Create"
-Draw%()="_bb_TgfxContractlist_Draw"
-DrawTapes%()="_bb_TgfxContractlist_DrawTapes"
-Update%()="_bb_TgfxContractlist_Update"
-SetOpen%(newState%)="_bb_TgfxContractlist_SetOpen"
}="bb_TgfxContractlist"
TAudienceQuotes^brl.blitz.Object{
List:brl.linkedlist.TList&=mem:p("_bb_TAudienceQuotes_List")
sheet:TTooltip&=mem:p("_bb_TAudienceQuotes_sheet")
.title$&
.audience%&
.audiencepercentage%&
.playerID%&
.sendhour%&
.sendminute%&
.senddate%&
-New%()="_bb_TAudienceQuotes_New"
+Load:TAudienceQuotes(pnode:xmlNode)="_bb_TAudienceQuotes_Load"
+LoadAll%()="_bb_TAudienceQuotes_LoadAll"
+SaveAll%()="_bb_TAudienceQuotes_SaveAll"
-Save%()="_bb_TAudienceQuotes_Save"
+Create:TAudienceQuotes(title$,audience!,audiencepercentage%,sendhour%,sendminute%,senddate%,playerID%)="_bb_TAudienceQuotes_Create"
-ShowSheet%(x%,y%)="_bb_TAudienceQuotes_ShowSheet"
+GetAudienceOfDate:TAudienceQuotes(playerID%,day%,hour%,minute%)="_bb_TAudienceQuotes_GetAudienceOfDate"
+GetAudienceOfDay:TAudienceQuotes&[](playerID%,day%)="_bb_TAudienceQuotes_GetAudienceOfDay"
}="bb_TAudienceQuotes"
TTooltip^TRenderable{
TooltipHeader:TGW_Sprites&=mem:p("_bb_TTooltip_TooltipHeader")
ToolTipIcons:brl.max2d.TImage&=mem:p("_bb_TTooltip_ToolTipIcons")
UseFontBold:brl.max2d.TImageFont&=mem:p("_bb_TTooltip_UseFontBold")
UseFont:brl.max2d.TImageFont&=mem:p("_bb_TTooltip_UseFont")
List:brl.linkedlist.TList&=mem:p("_bb_TTooltip_List")
.lifetime#&
.startlifetime#&
.title$&
.text$&
.oldtitle$&
.x%&
.y%&
.width%&
.height%&
.Image:brl.max2d.TImage&
.DirtyImage@&
.tooltipimage%&
.TitleBGtype@&
.enabled%&
-New%()="_bb_TTooltip_New"
+Create:TTooltip(title$=$"",text$=$"unknown",x%=0,y%=0,width%=-1,Height%=-1,lifetime%=1000)="_bb_TTooltip_Create"
-Update%(deltaTime#=1#)="_bb_TTooltip_Update"
-GetWidth%()="_bb_TTooltip_GetWidth"
-DrawShadow%(_width#,_height#)="_bb_TTooltip_DrawShadow"
-Draw%(tweenValue#=1#)="_bb_TTooltip_Draw"
}="bb_TTooltip"
DrawDialog%(gfx_Rect:TGW_SpritePack,x%,y%,width%,Height%,DialogStart$=$"StartDownLeft",DialogStartMove%=0,DialogText$=$"",DialogFont:brl.max2d.TImageFont="bbNullObject")="bb_DrawDialog"
DrawGFXRect%(gfx_Rect:TGW_SpritePack,x%,y%,width%,Height%)="bb_DrawGFXRect"
TBlock^brl.blitz.Object{
.dragable%&
.dragged%&
.Pos:TPosition&
.OrigPos:TPosition&
.StartPos:TPosition&
.StartPosBackup:TPosition&
.owner%&
.Height%&
.width%&
-New%()="_bb_TBlock_New"
-SwitchBlock%(otherObj:TBlock)="_bb_TBlock_SwitchBlock"
-SwitchCoords%(otherObj:TBlock)="_bb_TBlock_SwitchCoords"
-ContainingCoord@(_x%,_y%)="_bb_TBlock_ContainingCoord"
-SetCoords%(_x%=1000,_y%=1000,_startx%=1000,_starty%=1000)="_bb_TBlock_SetCoords"
-SetBaseCoords%(_x%=1000,_y%=1000)="_bb_TBlock_SetBaseCoords"
-IsAtStartPos%()="_bb_TBlock_IsAtStartPos"
}="bb_TBlock"
TFader^brl.blitz.Object{
.fadecount!&
.fadeout%&
.fadeenabled%&
-New%()="_bb_TFader_New"
-Enable%()="_bb_TFader_Enable"
-EnableFadeout%()="_bb_TFader_EnableFadeout"
-Update%(deltaTime#=1#)="_bb_TFader_Update"
-Draw%(deltaTime#=1#)="_bb_TFader_Draw"
}="bb_TFader"
TError^brl.blitz.Object{
List:brl.linkedlist.TList&=mem:p("_bb_TError_List")
LastID%&=mem("_bb_TError_LastID")
.title$&
.message$&
.id%&
.link:brl.linkedlist.TLink&
-New%()="_bb_TError_New"
+Create:TError(title$,message$)="_bb_TError_Create"
+CreateNotEnoughMoneyError%()="_bb_TError_CreateNotEnoughMoneyError"
+DrawErrors%()="_bb_TError_DrawErrors"
+UpdateErrors%()="_bb_TError_UpdateErrors"
-UpdateError%()="_bb_TError_UpdateError"
+DrawNewError%(str$=$"unknown error")="_bb_TError_DrawNewError"
-DrawError%()="_bb_TError_DrawError"
}="bb_TError"
TDialogueAnswer^brl.blitz.Object{
._text$&
._leadsTo%&
._func$(param%)&
._funcparam%&
-New%()="_bb_TDialogueAnswer_New"
+Create:TDialogueAnswer(text$,leadsTo%=0,_func$(param%)="brl_blitz_NullFunctionError",_funcparam%=0)="_bb_TDialogueAnswer_Create"
-Update%(x#,y#,w#,h#,clicked%=0)="_bb_TDialogueAnswer_Update"
-Draw%(x#,y#,w#,h#)="_bb_TDialogueAnswer_Draw"
}="bb_TDialogueAnswer"
TDialogueTexts^brl.blitz.Object{
._text$&
._answers:brl.linkedlist.TList&
._goTo%&
-New%()="_bb_TDialogueTexts_New"
+Create:TDialogueTexts(text$)="_bb_TDialogueTexts_Create"
-AddAnswer%(answer:TDialogueAnswer)="_bb_TDialogueTexts_AddAnswer"
-Update%(x#,y#,w#,h#,clicked%=0)="_bb_TDialogueTexts_Update"
-Draw%(x#,y#,w#,h#)="_bb_TDialogueTexts_Draw"
}="bb_TDialogueTexts"
TDialogue^brl.blitz.Object{
._texts:brl.linkedlist.TList&
._currentText%&
._x#&
._y#&
._w#&
._h#&
-New%()="_bb_TDialogue_New"
+Create:TDialogue(x#,y#,w#,h#)="_bb_TDialogue_Create"
-AddText%(Text:TDialogueTexts)="_bb_TDialogue_AddText"
-Update%(isMouseHit%=0)="_bb_TDialogue_Update"
-Draw%()="_bb_TDialogue_Draw"
}="bb_TDialogue"
TButton^brl.blitz.Object{
UseFont:brl.max2d.TImageFont&=mem:p("_bb_TButton_UseFont")
List:brl.linkedlist.TList&=mem:p("_bb_TButton_List")
.x%&
.y%&
.w%&
.h%&
.id%&
.image:brl.max2d.TImage&
.Sprite:TGW_Sprites&
.Caption$&
.enabled%&
.Clicked%&
.fontr%&
.fontg%&
.fontb%&
-New%()="_bb_TButton_New"
-IsIn%(_x%,_y%)="_bb_TButton_IsIn"
-OnClick%()A="brl_blitz_NullMethodError"
-Draw%(tweenValue#=1#)="_bb_TButton_Draw"
}A="bb_TButton"
TPPbuttons^TButton{
List:brl.linkedlist.TList&=mem:p("_bb_TPPbuttons_List")
-New%()="_bb_TPPbuttons_New"
+Create:TPPbuttons(sprite:TGW_Sprites,_caption$=$"",x%,y%,id%,own%=0)="_bb_TPPbuttons_Create"
+DrawAll%()="_bb_TPPbuttons_DrawAll"
+UpdateAll%()="_bb_TPPbuttons_UpdateAll"
-OnClick%()="_bb_TPPbuttons_OnClick"
}="bb_TPPbuttons"
TNewsbuttons^TButton{
List:brl.linkedlist.TList&=mem:p("_bb_TNewsbuttons_List")
.frameNr%&
.genre%&
.owner%&
.clickstate%&
.tooltip:TTooltip&
-New%()="_bb_TNewsbuttons_New"
+Create:TNewsbuttons(frameNr%=0,genre%=0,_caption$=$"",owner%=0,x%,y%,id%)="_bb_TNewsbuttons_Create"
+GetButton:TNewsbuttons(genre%,owner%)="_bb_TNewsbuttons_GetButton"
+UpdateAll%(deltaTime#=1#)="_bb_TNewsbuttons_UpdateAll"
-OnClick%()="_bb_TNewsbuttons_OnClick"
-Draw%(tweenValue#=1#)="_bb_TNewsbuttons_Draw"
}="bb_TNewsbuttons"
TInterface^brl.blitz.Object{
InterfaceList:brl.linkedlist.TList&=mem:p("_bb_TInterface_InterfaceList")
.gfx_bottomRTT:brl.max2d.TImage&
.ActualProgram:TGW_Sprites&
.ActualAudience:brl.max2d.TImage&
.ActualNoise:TGW_Sprites&
.ActualProgramText$&
.ActualProgramToolTip:TTooltip&
.ActualAudienceToolTip:TTooltip&
.NoiseAlpha#&
.ChangeNoiseTimer#&
.ShowChannel@&
.BottomImgDirty@&
-New%()="_bb_TInterface_New"
+Create:TInterface()="_bb_TInterface_Create"
-Update%(deltaTime#=1#)="_bb_TInterface_Update"
-Draw%(tweenValue#=1#)="_bb_TInterface_Draw"
}="bb_TInterface"
TStation^brl.blitz.Object{
_lastID%&=mem("_bb_TStation__lastID")
.x%&
.y%&
.reach%&
.price%&
.owner%&
.id%&
-New%()="_bb_TStation_New"
+Create:TStation(x%,y%,reach%,price%,owner%)="_bb_TStation_Create"
-GetNewID%()="_bb_TStation_GetNewID"
+GetPrice%(summe%)="_bb_TStation_GetPrice"
+Load:TStation(pnode:xmlNode)="_bb_TStation_Load"
-Save%()="_bb_TStation_Save"
-Draw%()="_bb_TStation_Draw"
}="bb_TStation"
TStationPoint^brl.blitz.Object{
.x%&
.y%&
.color%&
-New%()="_bb_TStationPoint_New"
+Create:TStationPoint(x%,y%,color%)="_bb_TStationPoint_Create"
}="bb_TStationPoint"
TStationMap^brl.blitz.Object{
List:brl.linkedlist.TList&=mem:p("_bb_TStationMap_List")
LastCalculatedAudienceSum%&=mem("_bb_TStationMap_LastCalculatedAudienceSum")
LastCalculatedAudienceIncrease%&=mem("_bb_TStationMap_LastCalculatedAudienceIncrease")
.StationList:brl.linkedlist.TList&
.radius%&
.owner:TPlayer&
.einwohner%&
.LastStationX%&
.LastStationY%&
.summe%&
.action%&
.pixmaparray%&[,]&
.bundesland$&
.outsideLand%&
.sellStation:TStation&[]&
.buyStation:TStation&[]&
.ShowStations%&[]&
.StationShare%&[,]&
-New%()="_bb_TStationMap_New"
+Load:TStationmap(pnode:xmlNode)="_bb_TStationMap_Load"
+LoadAll%()="_bb_TStationMap_LoadAll"
+SaveAll%()="_bb_TStationMap_SaveAll"
+Create:TStationMap()="_bb_TStationMap_Create"
-AddStation%(x%,y%,playerid%,valuetorefresh% Var)="_bb_TStationMap_AddStation"
-Buy%(x#,y#,playerid%=1)="_bb_TStationMap_Buy"
-Sell%(station:TStation)="_bb_TStationMap_Sell"
-CalculateStationCosts%(owner%=0)="_bb_TStationMap_CalculateStationCosts"
-Update%()="_bb_TStationMap_Update"
-DrawStations%()="_bb_TStationMap_DrawStations"
-Draw%()="_bb_TStationMap_Draw"
-calculateDistance!(x1%,y1%,x2%,y2%)="_bb_TStationMap_calculateDistance"
-CalculateShareNOTFINISHED%(playerA%,playerB%)="_bb_TStationMap_CalculateShareNOTFINISHED"
-CalculateAudienceIncrease%(owner%=0,_x%,_y%)="_bb_TStationMap_CalculateAudienceIncrease"
-CalculateAudienceSum%(owner%=0)="_bb_TStationMap_CalculateAudienceSum"
-CalculateStationRange%(mausX%,mausY%,radius%,x%,y%,width%,height%)="_bb_TStationMap_CalculateStationRange"
}="bb_TStationMap"
TRooms^brl.blitz.Object{
ActiveRoom:TRooms&=mem:p("_bb_TRooms_ActiveRoom")
RoomList:brl.linkedlist.TList&=mem:p("_bb_TRooms_RoomList")
LastID%&=mem("_bb_TRooms_LastID")
doadraw%&=mem("_bb_TRooms_doadraw")
DoorsDrawnToBackground%&=mem("_bb_TRooms_DoorsDrawnToBackground")
ActiveBackground:TGW_Sprites&=mem:p("_bb_TRooms_ActiveBackground")
ActiveBackgroundID%&=mem("_bb_TRooms_ActiveBackgroundID")
.background:TGW_Sprites&
.name$&
.desc$&
.descTwo$&
.DoorOpenTimer%&
.Pos:TPosition&
.xpos%&
.doortype%&
.doorwidth%&
.originaldoortype%&
.RoomSign:TRoomSigns&
.owner%&
.tooltip:TTooltip&
.uniqueID%&
.FadeAnimationActive%&
.RoomBoardX%&
.Dialogues:brl.linkedlist.TList&
-New%()="_bb_TRooms_New"
+ResetRoomSigns%()="_bb_TRooms_ResetRoomSigns"
-RemoveRoom%()="_bb_TRooms_RemoveRoom"
-CloseDoor%()="_bb_TRooms_CloseDoor"
-OpenDoor%()="_bb_TRooms_OpenDoor"
+CloseAllDoors%()="_bb_TRooms_CloseAllDoors"
+GetClickedRoom:TRooms(Figure:TFigures)="_bb_TRooms_GetClickedRoom"
+DrawDoorToolTips%()="_bb_TRooms_DrawDoorToolTips"
+UpdateDoorToolTips%(deltaTime#)="_bb_TRooms_UpdateDoorToolTips"
+DrawDoorsOnBackground%()="_bb_TRooms_DrawDoorsOnBackground"
+DrawDoors%()="_bb_TRooms_DrawDoors"
-Draw%()="_bb_TRooms_Draw"
-LeaveAnimated%(dontleave%)="_bb_TRooms_LeaveAnimated"
-Update%(draw@=0)="_bb_TRooms_Update"
-DrawActiveOne%()="_bb_TRooms_DrawActiveOne"
+Create:TRooms(background:TGW_Sprites,name$=$"unknown",desc$=$"unknown",descTwo$=$"",x%=0,y%=0,doortype%=-1,owner%=-1,createATooltip%=0)="_bb_TRooms_Create"
-CreateTooltip%(myx%=0)="_bb_TRooms_CreateTooltip"
+CreateWithPos:TRooms(background:TGW_Sprites,name$=$"unknown",desc$=$"unknown",x%=0,xpos%=0,width%=0,y%=0,doortype%=-1,owner%=-1,createATooltip%=0)="_bb_TRooms_CreateWithPos"
+GetRoomFromID:TRooms(ID%)="_bb_TRooms_GetRoomFromID"
+GetRandomReachableRoom:TRooms()="_bb_TRooms_GetRandomReachableRoom"
+GetRoomFromXY:TRooms(x%,y%)="_bb_TRooms_GetRoomFromXY"
+GetRoomFromMapPos:TRooms(x%,y%)="_bb_TRooms_GetRoomFromMapPos"
+GetRoom:TRooms(desc$,owner%)="_bb_TRooms_GetRoom"
}="bb_TRooms"
Room_News_Compute%(_room:TRooms)="bb_Room_News_Compute"
Room_Office_Compute%(_room:TRooms)="bb_Room_Office_Compute"
Room_Safe_Compute%(_room:TRooms)="bb_Room_Safe_Compute"
Room_Financials_Compute%(_room:TRooms)="bb_Room_Financials_Compute"
Room_Image_Compute%(_room:TRooms)="bb_Room_Image_Compute"
Room_Elevator_Compute%(_room:TRooms)="bb_Room_Elevator_Compute"
Room_RoomBoard_Compute%(_room:TRooms)="bb_Room_RoomBoard_Compute"
Room_AdAgency_Compute%(_room:TRooms)="bb_Room_AdAgency_Compute"
Room_MovieAgency_Compute%(_room:TRooms)="bb_Room_MovieAgency_Compute"
Room_MovieAuction_Compute%(_room:TRooms)="bb_Room_MovieAuction_Compute"
Room_Betty_Compute%(_room:TRooms)="bb_Room_Betty_Compute"
Room_Chief_Compute%(_room:TRooms)="bb_Room_Chief_Compute"
OnClick_StationMapSell%(sender:Object)="bb_OnClick_StationMapSell"
OnClick_StationMapSellApprove%(sender:Object)="bb_OnClick_StationMapSellApprove"
OnClick_StationMapNew%(sender:Object)="bb_OnClick_StationMapNew"
OnClick_StationMapBuy%(sender:Object)="bb_OnClick_StationMapBuy"
OnUpdate_StationMapBuy%(sender:Object)="bb_OnUpdate_StationMapBuy"
OnUpdate_StationMapSell%(sender:Object)="bb_OnUpdate_StationMapSell"
OnUpdate_StationMapList%(sender:Object)="bb_OnUpdate_StationMapList"
OnUpdate_StationMapFilters%(sender:Object)="bb_OnUpdate_StationMapFilters"
Room_StationMap_Compute%(_room:TRooms)="bb_Room_StationMap_Compute"
Room_NewsPlanner_Compute%(_room:TRooms)="bb_Room_NewsPlanner_Compute"
Room_ProgrammePlanner_Compute%(_room:TRooms)="bb_Room_ProgrammePlanner_Compute"
Room_Archive_Compute%(_room:TRooms)="bb_Room_Archive_Compute"
TRoomSigns^TBlock{
DragAndDropList:brl.linkedlist.TList&=mem:p("_bb_TRoomSigns_DragAndDropList")
List:brl.linkedlist.TList&=mem:p("_bb_TRoomSigns_List")
AdditionallyDragged%&=mem("_bb_TRoomSigns_AdditionallyDragged")
DebugMode@&=mem:b("_bb_TRoomSigns_DebugMode")
.title$&
.image:TGW_Sprites&
.imageWithText:TGW_Sprites&
.image_dragged:TGW_Sprites&
-New%()="_bb_TRoomSigns_New"
+Create:TRoomSigns(text$=$"unknown",x%=0,y%=0,owner%=0)="_bb_TRoomSigns_Create"
-SetDragable%(_dragable%=1)="_bb_TRoomSigns_SetDragable"
-Compare%(otherObject:Object)="_bb_TRoomSigns_Compare"
-GetSlotOfBlock%()="_bb_TRoomSigns_GetSlotOfBlock"
-Draw%()="_bb_TRoomSigns_Draw"
+UpdateAll%(DraggingAllowed@)="_bb_TRoomSigns_UpdateAll"
+DrawAll%()="_bb_TRoomSigns_DrawAll"
+GetRoomPosFromXY%(_x%,_y%)="_bb_TRoomSigns_GetRoomPosFromXY"
}="bb_TRoomSigns"
Init_CreateAllRooms%()="bb_Init_CreateAllRooms"
Init_SetRoomNames%()="bb_Init_SetRoomNames"
Init_CreateRoomTooltips%()="bb_Init_CreateRoomTooltips"
TNewLuaEngine^brl.blitz.Object{
-New%()="_bb_TNewLuaEngine_New"
+Create:TNewLuaEngine()="_bb_TNewLuaEngine_Create"
+LuaState@*()="_bb_TNewLuaEngine_LuaState"
-KillLuaState%()="_bb_TNewLuaEngine_KillLuaState"
-RegisterFunction%(functionName$,_func@*)="_bb_TNewLuaEngine_RegisterFunction"
-RegisterConstantInt%(variableName$,_variable%)="_bb_TNewLuaEngine_RegisterConstantInt"
-RegisterConstantFloat%(variableName$,_variable!)="_bb_TNewLuaEngine_RegisterConstantFloat"
-LoadScript%(scriptFile$)="_bb_TNewLuaEngine_LoadScript"
-CallFunction%(functionName$)="_bb_TNewLuaEngine_CallFunction"
-fileToString$(filename$)="_bb_TNewLuaEngine_fileToString"
}="bb_TNewLuaEngine"
TLuaEngine^brl.blitz.Object{
._LuaClass:brl.maxlua.TLuaClass&
._LuaInstance:brl.maxlua.TLuaObject&
-New%()="_bb_TLuaEngine_New"
+Create:TLuaEngine()="_bb_TLuaEngine_Create"
-LoadSource%(source$)="_bb_TLuaEngine_LoadSource"
-CallLuaFunction%(name$,params:Object&[]="bbEmptyArray")="_bb_TLuaEngine_CallLuaFunction"
-RegisterBlitzmaxObject%(Obj:Object,ObjName$)="_bb_TLuaEngine_RegisterBlitzmaxObject"
}="bb_TLuaEngine"
getLuaEngine:TLuaEngine()="bb_getLuaEngine"
KI^brl.blitz.Object{
.playerId@&
.LuaEngine:TLuaEngine&
.scriptName$&
.scriptAsString$&
.scriptConstants$&
.MyLuaState@*&
.inRoom@&
.LastErrorNumber%&
-New%()="_bb_KI_New"
+Create:KI(pId@,script$)="_bb_KI_Create"
-PrintErrors%()="_bb_KI_PrintErrors"
-Stop%()="_bb_KI_Stop"
-reloadScript%()="_bb_KI_reloadScript"
-initScriptVariables%()="_bb_KI_initScriptVariables"
-CallOnLoad%(savedluascript$=$"")="_bb_KI_CallOnLoad"
-CallOnSave%()="_bb_KI_CallOnSave"
-CallOnMinute%()="_bb_KI_CallOnMinute"
-CallOnChat%(text$=$"")="_bb_KI_CallOnChat"
-CallOnReachRoom%(roomId@)="_bb_KI_CallOnReachRoom"
-CallOnLeaveRoom%()="_bb_KI_CallOnLeaveRoom"
-CallOnDayBegins%()="_bb_KI_CallOnDayBegins"
-CallOnMoneyChanged%()="_bb_KI_CallOnMoneyChanged"
-fileToString$(filename$)="_bb_KI_fileToString"
-addScriptConstant%(name$,value$)="_bb_KI_addScriptConstant"
}="bb_KI"
TLuaFunctions^brl.blitz.Object{
-New%()="_bb_TLuaFunctions_New"
+Lua_GetString$(luaState@*)="_bb_TLuaFunctions_Lua_GetString"
+Lua_GetDouble!(luaState@*)="_bb_TLuaFunctions_Lua_GetDouble"
-PrintOut%(text$)="_bb_TLuaFunctions_PrintOut"
-SendToChat%(ChatText$)="_bb_TLuaFunctions_SendToChat"
-GetPlayerPosX%(PlayerID%=0)="_bb_TLuaFunctions_GetPlayerPosX"
-GetPlayerTargetPosX%(PlayerID%=0)="_bb_TLuaFunctions_GetPlayerTargetPosX"
-SetPlayerTargetPosX%(PlayerID%=0,newTargetX%=0)="_bb_TLuaFunctions_SetPlayerTargetPosX"
-getMillisecs%()="_bb_TLuaFunctions_getMillisecs"
-getTime%()="_bb_TLuaFunctions_getTime"
-getPlayerMaxAudience%()="_bb_TLuaFunctions_getPlayerMaxAudience"
-getPlayerAudience%()="_bb_TLuaFunctions_getPlayerAudience"
-getPlayerCredit%()="_bb_TLuaFunctions_getPlayerCredit"
-getPlayerMoney%()="_bb_TLuaFunctions_getPlayerMoney"
-getPlayerRoom%()="_bb_TLuaFunctions_getPlayerRoom"
-getPlayerTargetRoom%()="_bb_TLuaFunctions_getPlayerTargetRoom"
-getPlayerFloor%()="_bb_TLuaFunctions_getPlayerFloor"
-getRoomFloor%(roomId%=0)="_bb_TLuaFunctions_getRoomFloor"
-doGoToRoom%(roomId%=0)="_bb_TLuaFunctions_doGoToRoom"
-Day%(_time%=0)="_bb_TLuaFunctions_Day"
-Hour%(_time%=0)="_bb_TLuaFunctions_Hour"
-Minute%(_time%=0)="_bb_TLuaFunctions_Minute"
-Weekday%(_time%=0)="_bb_TLuaFunctions_Weekday"
-MovieSequels%(movieId%=-1)="_bb_TLuaFunctions_MovieSequels"
-MovieFromSerie%(serieId%=-1,episode%=0)="_bb_TLuaFunctions_MovieFromSerie"
-MoviePrice%(movieId%=-1)="_bb_TLuaFunctions_MoviePrice"
-MovieGenre%(movieId%=-1)="_bb_TLuaFunctions_MovieGenre"
-MovieLength%(movieId%=-1)="_bb_TLuaFunctions_MovieLength"
-MovieXRated%(movieId%=-1)="_bb_TLuaFunctions_MovieXRated"
-MovieProfit%(movieId%=-1)="_bb_TLuaFunctions_MovieProfit"
-MovieSpeed%(movieId%=-1)="_bb_TLuaFunctions_MovieSpeed"
-LUA_MovieReview%(movieId%=-1)="_bb_TLuaFunctions_LUA_MovieReview"
-MovieTopicality%(movieId%=-1)="_bb_TLuaFunctions_MovieTopicality"
-SpotAudience%(spotId%=-1)="_bb_TLuaFunctions_SpotAudience"
-SpotToSend%(spotId%=-1)="_bb_TLuaFunctions_SpotToSend"
-SpotMaxDays%(spotId%=-1)="_bb_TLuaFunctions_SpotMaxDays"
-LUA_SpotProfit%(spotId%=-1)="_bb_TLuaFunctions_LUA_SpotProfit"
-SpotPenalty%(spotId%=-1)="_bb_TLuaFunctions_SpotPenalty"
-SpotTargetgroup%(spotId%=-1)="_bb_TLuaFunctions_SpotTargetgroup"
-of_getMovie%(day%=-1,hour%=-1)="_bb_TLuaFunctions_of_getMovie"
-of_getSpot%(day%=-1,hour%=-1)="_bb_TLuaFunctions_of_getSpot"
-of_getPlayerSpotCount%()="_bb_TLuaFunctions_of_getPlayerSpotCount"
-of_getPlayerSpot%(arraynumber%=-1)="_bb_TLuaFunctions_of_getPlayerSpot"
-of_getSpotWillBeSent%(day%=-1,hour%=-1)="_bb_TLuaFunctions_of_getSpotWillBeSent"
-of_getSpotBeenSent%(contractID%=-1)="_bb_TLuaFunctions_of_getSpotBeenSent"
-of_getSpotDaysLeft%(contractID%=-1)="_bb_TLuaFunctions_of_getSpotDaysLeft"
-of_doMovieInPlan%(day%=-1,hour%=-1,ObjectID%=-1)="_bb_TLuaFunctions_of_doMovieInPlan"
-doSpotInPlan%(day%=-1,hour%=-1,ObjectID%=-1)="_bb_TLuaFunctions_doSpotInPlan"
-getEvaluatedAudienceQuote%(hour%=-1,ObjectID%=-1)="_bb_TLuaFunctions_getEvaluatedAudienceQuote"
-sa_getSpotCount%()="_bb_TLuaFunctions_sa_getSpotCount"
-sa_getSpot%(ArrayID%=-1)="_bb_TLuaFunctions_sa_getSpot"
-md_getMovieCount%()="_bb_TLuaFunctions_md_getMovieCount"
-md_getMovie%(ArrayID%=-1)="_bb_TLuaFunctions_md_getMovie"
-md_doBuyMovie%(ObjektID%=-1)="_bb_TLuaFunctions_md_doBuyMovie"
}="bb_TLuaFunctions"
KI_EventManager^brl.blitz.Object{
registeredKIs:brl.linkedlist.TList&=mem:p("_bb_KI_EventManager_registeredKIs")
-New%()="_bb_KI_EventManager_New"
+getKIByPlayerId:KI(playerId@)="_bb_KI_EventManager_getKIByPlayerId"
+registerKI%(ki:KI)="_bb_KI_EventManager_registerKI"
+unregisterKI%(ki:KI)="_bb_KI_EventManager_unregisterKI"
+onMinute%(playerId@)="_bb_KI_EventManager_onMinute"
+onReachRoom%(playerId@,roomId@)="_bb_KI_EventManager_onReachRoom"
+onLeaveRoom%(playerId@,roomId@)="_bb_KI_EventManager_onLeaveRoom"
+onDayBegins%(playerId@)="_bb_KI_EventManager_onDayBegins"
-onMoneyChanged%(playerId@)="_bb_KI_EventManager_onMoneyChanged"
}="bb_KI_EventManager"
TApp^brl.blitz.Object{
.Timer:TDeltaTimer&
.limitFrames%&
.height%&
.width%&
-New%()="_bb_TApp_New"
+Create:TApp(physicsFps%=60,limitFrames%=0,width%=800,height%=600)="_bb_TApp_Create"
}="bb_TApp"
TGame^brl.blitz.Object{
List:brl.linkedlist.TList&=mem:p("_bb_TGame_List")
.debugmode@&
.DebugInfos@&
.speed#&
.oldspeed#&
.DoorOpenTime%&
.minutesOfDayGone#&
.lastMinutesOfDayGone#&
.timeSinceBegin#&
.year%&
.day%&
.minute%&
.hour%&
.cursorstate%&
.playerID%&
.start_MovieAmount%&
.start_AdAmount%&
.error%&
.maxAudiencePercentage#&
.maxContractsAllowed%&
.maxMoviesInSuitcaseAllowed%&
.gamestate%&
.networkgame%&
.networkgameready%&
.onlinegame%&
.title$&
.daytoplan%&
.daynames$&[]&
.daynames_long$&[]&
.fullscreen%&
.username$&
.userport@@&
.userchannelname$&
.userlanguage$&
.userdb$&
.userfallbackip$&
-New%()="_bb_TGame_New"
+REMOVE_Save%()="_bb_TGame_REMOVE_Save"
+REMOVE_Load%()="_bb_TGame_REMOVE_Load"
+SaveGame%(savename$=$"savegame.xml")="_bb_TGame_SaveGame"
+LoadGame%(savename$=$"save")="_bb_TGame_LoadGame"
+Create:TGame()="_bb_TGame_Create"
-LoadConfig@(configfile$=$"config/settings.xml")="_bb_TGame_LoadConfig"
-getNextHour%()="_bb_TGame_getNextHour"
-Update%(deltaTime#=1#)="_bb_TGame_Update"
-GetFormattedDay$(_day%=-5)="_bb_TGame_GetFormattedDay"
-GetFormattedDayLong$(_day%=-5)="_bb_TGame_GetFormattedDayLong"
-GetFormattedTime$()="_bb_TGame_GetFormattedTime"
-GetFormattedExternTime$(hour%,_minute%)="_bb_TGame_GetFormattedExternTime"
-GetActualDay%(_time%=0)="_bb_TGame_GetActualDay"
-GetActualMinute%(_time%=0)="_bb_TGame_GetActualMinute"
-GetActualHour%(_time%=0)="_bb_TGame_GetActualHour"
}="bb_TGame"
TPlayer^brl.blitz.Object{
globalID%&=mem("_bb_TPlayer_globalID")
List:brl.linkedlist.TList&=mem:p("_bb_TPlayer_List")
.Name$&
.channelname$&
.finances:TFinancials&[]&
.audience%&
.maxaudience%&
.ProgrammeCollection:TPlayerProgrammeCollection&
.ProgrammePlan:TPlayerProgrammePlan&
.ActualProgramme:TProgramme&
.ActualContract:TContract&
.Figure:TFigures&
.playerID%&
.color:TPlayerColor&
.figurebase%&
.networkstate%&
.newsabonnements%&[]&
.PlayerKI:KI&
.CreditCurrent%&
.CreditMaximum%&
-New%()="_bb_TPlayer_New"
+Load:Tplayer(pnode:xmlNode)="_bb_TPlayer_Load"
+LoadAll%()="_bb_TPlayer_LoadAll"
+SaveAll%()="_bb_TPlayer_SaveAll"
-Save%()="_bb_TPlayer_Save"
+Create:TPlayer(Name$,channelname$=$"",ImageOrSprite:Object,x%,onFloor%=13,dx%,pcolr%,pcolg%,pcolb%,ControlledByID%=1,FigureName$=$"")="_bb_TPlayer_Create"
-UpdateFigureBase%(newfigurebase%)="_bb_TPlayer_UpdateFigureBase"
-RecolorFigure%(PlayerColor:TPlayerColor)="_bb_TPlayer_RecolorFigure"
-UpdateFinances%()="_bb_TPlayer_UpdateFinances"
-GetAudiencePercentage%()="_bb_TPlayer_GetAudiencePercentage"
-GetCreditAvaiable%()="_bb_TPlayer_GetCreditAvaiable"
-GetCreditCurrent%()="_bb_TPlayer_GetCreditCurrent"
+extSetCredit$(amount%)="_bb_TPlayer_extSetCredit"
-SetCredit%(amount%)="_bb_TPlayer_SetCredit"
+ComputeDailyCosts%()="_bb_TPlayer_ComputeDailyCosts"
+ComputeAds%()="_bb_TPlayer_ComputeAds"
+ComputeContractPenalties%()="_bb_TPlayer_ComputeContractPenalties"
+ComputeAudience%(recompute%=0)="_bb_TPlayer_ComputeAudience"
+ComputeNewsAudience%()="_bb_TPlayer_ComputeNewsAudience"
-Update%()="_bb_TPlayer_Update"
-GetFormattedMoney$()="_bb_TPlayer_GetFormattedMoney"
-GetRawMoney%()="_bb_TPlayer_GetRawMoney"
-GetFormattedCredit$()="_bb_TPlayer_GetFormattedCredit"
-GetFormattedAudience$()="_bb_TPlayer_GetFormattedAudience"
-Compare%(otherObject:Object)="_bb_TPlayer_Compare"
}="bb_TPlayer"
TFinancials^brl.blitz.Object{
List:brl.linkedlist.TList&=mem:p("_bb_TFinancials_List")
.paid_movies%&
.paid_stations%&
.paid_scripts%&
.paid_productionstuff%&
.paid_penalty%&
.paid_rent%&
.paid_news%&
.paid_newsagencies%&
.paid_stationfees%&
.paid_misc%&
.paid_total%&
.sold_movies%&
.sold_ads%&
.sold_misc%&
.sold_total%&
.sold_stations%&
.revenue_interest%&
.revenue_before%&
.revenue_after%&
.money%&
.credit%&
.playerID%&
.ListLink:brl.linkedlist.TLink&
-New%()="_bb_TFinancials_New"
+Load:TFinancials(pnode:xmlNode,finance:TFinancials)="_bb_TFinancials_Load"
+LoadAll%()="_bb_TFinancials_LoadAll"
+SaveAll%()="_bb_TFinancials_SaveAll"
-Save%()="_bb_TFinancials_Save"
+Create:TFinancials(playerID%,startmoney%=550000,startcredit%=250000)="_bb_TFinancials_Create"
+GetDayArray%(day%)="_bb_TFinancials_GetDayArray"
-SellMisc%(_money%)="_bb_TFinancials_SellMisc"
-SellStation%(_money%)="_bb_TFinancials_SellStation"
-ChangeMoney%(_moneychange%)="_bb_TFinancials_ChangeMoney"
-SellAds%(_money%)="_bb_TFinancials_SellAds"
-SellMovie%(_money%)="_bb_TFinancials_SellMovie"
-PayProgrammeBid@(_money%)="_bb_TFinancials_PayProgrammeBid"
-GetProgrammeBid%(_money%)="_bb_TFinancials_GetProgrammeBid"
-PayMovie@(_money%)="_bb_TFinancials_PayMovie"
-PayStation@(_money%)="_bb_TFinancials_PayStation"
-PayScript@(_money%)="_bb_TFinancials_PayScript"
-PayProductionStuff@(_money%)="_bb_TFinancials_PayProductionStuff"
-PayPenalty%(_money%)="_bb_TFinancials_PayPenalty"
-PayRent%(_money%)="_bb_TFinancials_PayRent"
-PayNews@(_money%)="_bb_TFinancials_PayNews"
-PayNewsAgencies%(_money%)="_bb_TFinancials_PayNewsAgencies"
-PayStationFees%(_money%)="_bb_TFinancials_PayStationFees"
-PayMisc%(_money%)="_bb_TFinancials_PayMisc"
}="bb_TFinancials"
CreateDropZones%()="bb_CreateDropZones"
TFloorRoute^brl.blitz.Object{
.floornumber%&
.call%&
.direction%&
.who%&
-New%()="_bb_TFloorRoute_New"
-Save%()="_bb_TFloorRoute_Save"
+Load:TFloorRoute(loadfile:brl.stream.TStream)="_bb_TFloorRoute_Load"
+Create:TFloorRoute(floornumber%,call%=0,who%=0,direction%=-1)="_bb_TFloorRoute_Create"
-Compare%(otherObject:Object)="_bb_TFloorRoute_Compare"
}="bb_TFloorRoute"
TElevator^brl.blitz.Object{
List:brl.linkedlist.TList&=mem:p("_bb_TElevator_List")
.PlanTime%&
.waitAtFloorTimer%&
.waitAtFloorTime%&
.spriteDoor:TAnimSprites&
.Image_inner:TGW_Sprites&
.passenger%&
.passengerFigure:TFigures&
.onFloor%&
.open%&
.toFloor%&
.speed#&
.Pos:TPosition&
.Parent:TBuilding&
.FloorRouteList:brl.linkedlist.TList&
.upwards%&
.EgoMode%&
-New%()="_bb_TElevator_New"
-ElevatorCallIsDuplicate%(floornumber%,who%)="_bb_TElevator_ElevatorCallIsDuplicate"
-Save%()="_bb_TElevator_Save"
-Load%(loadfile:brl.stream.TStream)="_bb_TElevator_Load"
+Create:TElevator(Parent:TBuilding)="_bb_TElevator_Create"
-AddFloorRoute%(floornumber%,call%=0,who%,First%=0,fromNetwork%=0)="_bb_TElevator_AddFloorRoute"
-GetFloorRoute%()="_bb_TElevator_GetFloorRoute"
-moveTo%(_tofloor%)="_bb_TElevator_moveTo"
-CloseDoor%()="_bb_TElevator_CloseDoor"
-OpenDoor%()="_bb_TElevator_OpenDoor"
-DrawFloorDoors%()="_bb_TElevator_DrawFloorDoors"
-Update%(deltaTime#=1#)="_bb_TElevator_Update"
-Draw%()="_bb_TElevator_Draw"
}="bb_TElevator"
TFigures^brl.blitz.Object{
LastID%&=mem("_bb_TFigures_LastID")
List:brl.linkedlist.TList&=mem:p("_bb_TFigures_List")
.Name$&
.pos:TPosition&
.lastDrawnPos:TPosition&
.dx#&
.initialdx#&
.targetx%&
.oldtargetx%&
.toFloor%&
.toRoom:TRooms&
.fromRoom:TRooms&
.clickedToRoom:TRooms&
.inRoom:TRooms&
.calledElevator%&
.onFloor%&
.id%&
.clickedToFloor%&
.xToElevator#&
.Visible%&
.image:brl.max2d.TImage&
.Sprite:TGW_Sprites&
.FrameWidth%&
.frameheight%&
.AnimPos%&
.NextTwinkerTimer%&
.NextAnimTimer%&
.NextAnimTime%&
.specialTime%&
.LastSpecialTime%&
.WaitTime%&
.BackupAnimTime%&
.inElevator@&
.ControlledByID%&
.alreadydrawn%&
.updatefunc_%(ListLink:brl.linkedlist.TLink,deltaTime#)&
.LastSync%&
.ListLink:brl.linkedlist.TLink&
.ParentPlayer:TPlayer&
.mylist:brl.linkedlist.TList&
-New%()="_bb_TFigures_New"
+Load:TFigures(pnode:xmlNode,figure:TFigures)="_bb_TFigures_Load"
+LoadAll%()="_bb_TFigures_LoadAll"
+AdditionalLoad%(obj:Object,node:xmlNode)="_bb_TFigures_AdditionalLoad"
+AdditionalSave%(obj:Object)="_bb_TFigures_AdditionalSave"
-FigureMovement%(deltaTime#=1#)="_bb_TFigures_FigureMovement"
-FigureAnimation%(deltaTime#=1#)="_bb_TFigures_FigureAnimation"
+UpdateBote%(ListLink:brl.linkedlist.TLink,deltaTime#=1#)="_bb_TFigures_UpdateBote"
+UpdateHausmeister%(ListLink:brl.linkedlist.TLink,deltaTime#=1#)="_bb_TFigures_UpdateHausmeister"
-GetPeopleOnSameFloor%()="_bb_TFigures_GetPeopleOnSameFloor"
-SetInRoom%(room:TRooms)="_bb_TFigures_SetInRoom"
-SetRoom%(room:TRooms)="_bb_TFigures_SetRoom"
-LeaveRoom%()="_bb_TFigures_LeaveRoom"
-SendToRoom%(room:TRooms)="_bb_TFigures_SendToRoom"
+GetFigure:TFigures(id%)="_bb_TFigures_GetFigure"
+Create:TFigures(FigureName$,imageOrSprite:Object,x%,onFloor%=13,dx%,ControlledByID%=-1)="_bb_TFigures_Create"
-IsOnFloor@()="_bb_TFigures_IsOnFloor"
-IsAtElevator@()="_bb_TFigures_IsAtElevator"
-IsInElevator@()="_bb_TFigures_IsInElevator"
-IsAI%()="_bb_TFigures_IsAI"
-CallElevator%()="_bb_TFigures_CallElevator"
-SendElevator%()="_bb_TFigures_SendElevator"
-ChangeTarget%(x%,_y%)="_bb_TFigures_ChangeTarget"
-Update%(deltaTime#=1#)="_bb_TFigures_Update"
+UpdateAll%(deltaTime#=1#)="_bb_TFigures_UpdateAll"
-GetDrawPosX#()="_bb_TFigures_GetDrawPosX"
-GetDrawPosY#()="_bb_TFigures_GetDrawPosY"
-Draw%()="_bb_TFigures_Draw"
}="bb_TFigures"
TBuilding^brl.blitz.Object{
StarsX%&[]&=mem:p("_bb_TBuilding_StarsX")
StarsY%&[]&=mem:p("_bb_TBuilding_StarsY")
StarsC%&[]&=mem:p("_bb_TBuilding_StarsC")
CloudPack:TSpritesPack&=mem:p("_bb_TBuilding_CloudPack")
List:brl.linkedlist.TList&=mem:p("_bb_TBuilding_List")
.x%&
.borderright%&
.borderleft%&
.y%&
.skycolor#&
.ufo_normal:TAnimSprites&
.ufo_beaming:TAnimSprites&
.Elevator:TElevator&
.Moon_curKubSplineX:appKubSpline&
.Moon_curKubSplineY:appKubSpline&
.Moon_curvStep#&
.Moon_tPos#&
.Moon_lastTChange%&
.Moon_setNewCurve%&
.Moon_newDataT%&[]&
.Moon_newDataX%&[]&
.Moon_newDataY%&[]&
.Moon_constSpeed%&
.Moon_pixelPerSecond#&
.ufo_curKubSplineX:appKubSpline&
.ufo_curKubSplineY:appKubSpline&
.ufo_curvStep#&
.ufo_tPos#&
.ufo_lastTChange%&
.ufo_setNewCurve%&
.ufo_newDataT%&[]&
.ufo_newDataX%&[]&
.ufo_newDataY%&[]&
.ufo_constSpeed%&
.ufo_pixelPerSecond#&
.Clouds:TSprites&[]&
.CloudCount%&
.TimeColor!&
.DezimalTime#&
.ActHour%&
.ItemsDrawnToBackground@&
-New%()="_bb_TBuilding_New"
+Create:TBuilding()="_bb_TBuilding_Create"
-Update%(deltaTime#=1#)="_bb_TBuilding_Update"
-DrawItemsToBackground%()="_bb_TBuilding_DrawItemsToBackground"
-Draw%(tweenValue#=1#)="_bb_TBuilding_Draw"
-UpdateBackground%(deltaTime#=1#)="_bb_TBuilding_UpdateBackground"
-DrawStars%(rndvalue%=0)="_bb_TBuilding_DrawStars"
-DrawBackground%(tweenValue#=1#)="_bb_TBuilding_DrawBackground"
-CenterToFloor%(floornumber%)="_bb_TBuilding_CenterToFloor"
-GetFloorY%(floornumber%)="_bb_TBuilding_GetFloorY"
-GetFloor%(_y%)="_bb_TBuilding_GetFloor"
}="bb_TBuilding"
TNewsAgency^brl.blitz.Object{
.LastEventTime#&
.NextEventTime#&
.LastNewsList:brl.linkedlist.TList&
-New%()="_bb_TNewsAgency_New"
-GetNextFromChain:TNews()="_bb_TNewsAgency_GetNextFromChain"
-AddNews%(news:TNews)="_bb_TNewsAgency_AddNews"
-AnnounceNewNews%()="_bb_TNewsAgency_AnnounceNewNews"
}="bb_TNewsAgency"
UpdateChat_GameSettings%()="bb_UpdateChat_GameSettings"
UpdateChat_InGame%()="bb_UpdateChat_InGame"
UpdateChat%(UseChat:TGuiChat)="bb_UpdateChat"
DrawAllSelectionRects%()="bb_DrawAllSelectionRects"
NetGameLobbyDoubleClick%(sender:Object)="bb_NetGameLobbyDoubleClick"
Menu_Main%()="bb_Menu_Main"
Menu_NetworkLobby%()="bb_Menu_NetworkLobby"
Menu_GameSettings%()="bb_Menu_GameSettings"
Menu_Main_Draw%()="bb_Menu_Main_Draw"
Menu_NetworkLobby_Draw%()="bb_Menu_NetworkLobby_Draw"
Menu_GameSettings_Draw%()="bb_Menu_GameSettings_Draw"
TBetty^brl.blitz.Object{
.InLove#&[]&
.LoveSum#&
.AwardWinner#&[]&
.AwardSum#&
.CurrentAwardType%&
.AwardEndingAtDay%&
.MaxAwardTypes%&
.AwardDuration%&
.LastAwardWinner%&
.LastAwardType%&
-New%()="_bb_TBetty_New"
-IncInLove%(PlayerID%,Amount#)="_bb_TBetty_IncInLove"
-IncAward%(PlayerID%,Amount#)="_bb_TBetty_IncAward"
-GetAwardTypeString$(AwardType%=0)="_bb_TBetty_GetAwardTypeString"
-SetAwardType%(AwardType%=0,SetEndingDay%=0,Duration%=0)="_bb_TBetty_SetAwardType"
-GetAwardEnding%()="_bb_TBetty_GetAwardEnding"
-GetRealLove%(PlayerID%)="_bb_TBetty_GetRealLove"
-GetLastAwardWinner%()="_bb_TBetty_GetLastAwardWinner"
-GetRealAward%(PlayerID%)="_bb_TBetty_GetRealAward"
}="bb_TBetty"
UpdateMenu%(deltaTime#=1#)="bb_UpdateMenu"
DrawMenu%(tweenValue#=1#)="bb_DrawMenu"
Init_Creation%()="bb_Init_Creation"
Init_Colorization%()="bb_Init_Colorization"
Init_All%()="bb_Init_All"
UpdateMain%(deltaTime#=1#)="bb_UpdateMain"
DrawMain%(tweenValue#=1#)="bb_DrawMain"
TEventOnTime^TEventBase{
.time%&
-New%()="_bb_TEventOnTime_New"
+Create:TEventOnTime(trigger$=$"",time%)="_bb_TEventOnTime_Create"
}="bb_TEventOnTime"
TEventListenerPlayer^TEventListenerBase{
.Player:TPlayer&
-New%()="_bb_TEventListenerPlayer_New"
+Create:TEventListenerPlayer(player:TPlayer)="_bb_TEventListenerPlayer_Create"
-OnEvent%(triggerEvent:TEventBase)="_bb_TEventListenerPlayer_OnEvent"
}="bb_TEventListenerPlayer"
TEventListenerOnMinute^TEventListenerBase{
-New%()="_bb_TEventListenerOnMinute_New"
+Create:TEventListenerOnMinute()="_bb_TEventListenerOnMinute_Create"
-OnEvent%(triggerEvent:TEventBase)="_bb_TEventListenerOnMinute_OnEvent"
}="bb_TEventListenerOnMinute"
TEventListenerOnDay^TEventListenerBase{
-New%()="_bb_TEventListenerOnDay_New"
+Create:TEventListenerOnDay()="_bb_TEventListenerOnDay_Create"
-OnEvent%(triggerEvent:TEventBase)="_bb_TEventListenerOnDay_OnEvent"
}="bb_TEventListenerOnDay"
TEventListenerOnAppUpdate^TEventListenerBase{
-New%()="_bb_TEventListenerOnAppUpdate_New"
+Create:TEventListenerOnAppUpdate()="_bb_TEventListenerOnAppUpdate_Create"
-OnEvent%(triggerEvent:TEventBase)="_bb_TEventListenerOnAppUpdate_OnEvent"
}="bb_TEventListenerOnAppUpdate"
TEventListenerOnAppDraw^TEventListenerBase{
-New%()="_bb_TEventListenerOnAppDraw_New"
+Create:TEventListenerOnAppDraw()="_bb_TEventListenerOnAppDraw_Create"
-OnEvent%(triggerEvent:TEventBase)="_bb_TEventListenerOnAppDraw_OnEvent"
}="bb_TEventListenerOnAppDraw"
TTVGNetwork^brl.blitz.Object{
HOSTPORT@&=mem:b("_bb_TTVGNetwork_HOSTPORT")
ONLINEPORT@&=mem:b("_bb_TTVGNetwork_ONLINEPORT")
LOCALPORT@&=mem:b("_bb_TTVGNetwork_LOCALPORT")
NET_ACK@&=mem:b("_bb_TTVGNetwork_NET_ACK")
NET_JOIN@&=mem:b("_bb_TTVGNetwork_NET_JOIN")
NET_PING@&=mem:b("_bb_TTVGNetwork_NET_PING")
NET_PONG@&=mem:b("_bb_TTVGNetwork_NET_PONG")
NET_UPDATE@&=mem:b("_bb_TTVGNetwork_NET_UPDATE")
NET_STATE@&=mem:b("_bb_TTVGNetwork_NET_STATE")
NET_QUIT@&=mem:b("_bb_TTVGNetwork_NET_QUIT")
NET_ANNOUNCEGAME@&=mem:b("_bb_TTVGNetwork_NET_ANNOUNCEGAME")
NET_SETSLOT@&=mem:b("_bb_TTVGNetwork_NET_SETSLOT")
NET_SLOTSET@&=mem:b("_bb_TTVGNetwork_NET_SLOTSET")
NET_PLAYERLIST@&=mem:b("_bb_TTVGNetwork_NET_PLAYERLIST")
NET_CHATMESSAGE@&=mem:b("_bb_TTVGNetwork_NET_CHATMESSAGE")
NET_PLAYERIPS@&=mem:b("_bb_TTVGNetwork_NET_PLAYERIPS")
NET_PLAYERDETAILS@&=mem:b("_bb_TTVGNetwork_NET_PLAYERDETAILS")
NET_PLAYERPOSITION@&=mem:b("_bb_TTVGNetwork_NET_PLAYERPOSITION")
NET_SENDPROGRAMME@&=mem:b("_bb_TTVGNetwork_NET_SENDPROGRAMME")
NET_GAMEREADY@&=mem:b("_bb_TTVGNetwork_NET_GAMEREADY")
NET_STARTGAME@&=mem:b("_bb_TTVGNetwork_NET_STARTGAME")
NET_PLAN_PROGRAMMECHANGE@&=mem:b("_bb_TTVGNetwork_NET_PLAN_PROGRAMMECHANGE")
NET_STATIONCHANGE@&=mem:b("_bb_TTVGNetwork_NET_STATIONCHANGE")
NET_ELEVATORROUTECHANGE@&=mem:b("_bb_TTVGNetwork_NET_ELEVATORROUTECHANGE")
NET_ELEVATORSYNCHRONIZE@&=mem:b("_bb_TTVGNetwork_NET_ELEVATORSYNCHRONIZE")
NET_PLAN_ADCHANGE@&=mem:b("_bb_TTVGNetwork_NET_PLAN_ADCHANGE")
NET_SENDCONTRACT@&=mem:b("_bb_TTVGNetwork_NET_SENDCONTRACT")
NET_PROGRAMMECOLLECTION_CHANGE@&=mem:b("_bb_TTVGNetwork_NET_PROGRAMMECOLLECTION_CHANGE")
NET_SENDNEWS@&=mem:b("_bb_TTVGNetwork_NET_SENDNEWS")
NET_NEWSSUBSCRIPTIONLEVEL@&=mem:b("_bb_TTVGNetwork_NET_NEWSSUBSCRIPTIONLEVEL")
NET_PLAN_NEWSCHANGE@&=mem:b("_bb_TTVGNetwork_NET_PLAN_NEWSCHANGE")
NET_MOVIEAGENCY_CHANGE@&=mem:b("_bb_TTVGNetwork_NET_MOVIEAGENCY_CHANGE")
NET_DELETE@&=mem:b("_bb_TTVGNetwork_NET_DELETE")
NET_ADD@&=mem:b("_bb_TTVGNetwork_NET_ADD")
NET_CHANGE@&=mem:b("_bb_TTVGNetwork_NET_CHANGE")
NET_BUY@&=mem:b("_bb_TTVGNetwork_NET_BUY")
NET_SELL@&=mem:b("_bb_TTVGNetwork_NET_SELL")
NET_BID@&=mem:b("_bb_TTVGNetwork_NET_BID")
NET_SWITCH@&=mem:b("_bb_TTVGNetwork_NET_SWITCH")
MyStream:brl.stream.TStream&=mem:p("_bb_TTVGNetwork_MyStream")
MyBank:brl.bank.TBank&=mem:p("_bb_TTVGNetwork_MyBank")
LastElevatorSynchronize%&=mem("_bb_TTVGNetwork_LastElevatorSynchronize")
BackupStreamPtr@*&=mem:p("_bb_TTVGNetwork_BackupStreamPtr")
BackupStreamSize%&=mem("_bb_TTVGNetwork_BackupStreamSize")
.SpeedFactor!&
.SpeedFactorLan!&
.SpeedFactorOnline!&
.isHost%&
.IsConnected%&
.ServerIP%&
.ServerPort%&
.MyIP$&
.intMyIP%&
.Stream:TUDPStream&
.myPing%&[]&
.PingTime%&[]&
.PingTimer%&
.UpdateTime%&
.MainSyncTime%&
.AnnounceTime%&
.SendID%&
.RecvID%&
.lastRecv%&[]&
.MyID%&
.IP%&[]&
.Port@@&[]&
.debugmode@&
.bSentFull@&
.n:NetObj&
.netList:brl.linkedlist.TList&
.LastOnlineRequestTimer%&
.LastOnlineRequestTime%&
.LastOnlineHashCode$&
.OnlineIP$&
.intOnlineIP%&
.ChatSpamTime%&
-New%()="_bb_TTVGNetwork_New"
+URLEncode$(txt$)="_bb_TTVGNetwork_URLEncode"
+URLDecode$(txt$)="_bb_TTVGNetwork_URLDecode"
-BackupStream%(toBank:brl.bank.TBank)="_bb_TTVGNetwork_BackupStream"
-RestoreStream%(fromBank:brl.bank.TBank)="_bb_TTVGNetwork_RestoreStream"
+Create:TTVGNetwork(fallbackip$)="_bb_TTVGNetwork_Create"
-GetFreeSlot%()="_bb_TTVGNetwork_GetFreeSlot"
+GetBroadcastIP$(ip$)="_bb_TTVGNetwork_GetBroadcastIP"
-IsNoComputerNorMe@(_IP%,_Port@@)="_bb_TTVGNetwork_IsNoComputerNorMe"
-WriteMyIP%()="_bb_TTVGNetwork_WriteMyIP"
-GetMyIP%()="_bb_TTVGNetwork_GetMyIP"
-GetMyPort@@()="_bb_TTVGNetwork_GetMyPort"
-SendChatMessage%(ChatMessage$=$"")="_bb_TTVGNetwork_SendChatMessage"
-SendPlayerIPs%()="_bb_TTVGNetwork_SendPlayerIPs"
-SendJoin%()="_bb_TTVGNetwork_SendJoin"
-SendGameAnnouncement%()="_bb_TTVGNetwork_SendGameAnnouncement"
-SendPlayerDetails@()="_bb_TTVGNetwork_SendPlayerDetails"
-SendPlayerPosition%()="_bb_TTVGNetwork_SendPlayerPosition"
-SendProgramme%(playerID%,programme:TProgramme&[])="_bb_TTVGNetwork_SendProgramme"
-SendMovieAgencyChange%(methodtype@,playerID%,newID%=-1,slot%=-1,programme:TProgramme)="_bb_TTVGNetwork_SendMovieAgencyChange"
-GotPacket_SendMovieAgencyChange%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_SendMovieAgencyChange"
-SendGameReady%(playerID%,onlyTo%=-1)="_bb_TTVGNetwork_SendGameReady"
-SendGameStart%()="_bb_TTVGNetwork_SendGameStart"
-SendPlanProgrammeChange%(playerID%,programmeBlock:TProgrammeBlock,add@=1)="_bb_TTVGNetwork_SendPlanProgrammeChange"
-SendContract%(playerID%,contract:TContract&[])="_bb_TTVGNetwork_SendContract"
-SendPlanAdChange%(playerID%,AdBlock:TAdBlock,add@=1)="_bb_TTVGNetwork_SendPlanAdChange"
-SendStationChange%(playerID%,station:TStation,newaudience%,add@=1)="_bb_TTVGNetwork_SendStationChange"
-SendElevatorSynchronize%()="_bb_TTVGNetwork_SendElevatorSynchronize"
-SendElevatorRouteChange%(floornumber%,call%=0,who%,First@=0)="_bb_TTVGNetwork_SendElevatorRouteChange"
-SendProgrammeCollectionChange%(playerID%,programme:TProgramme,typ@=0)="_bb_TTVGNetwork_SendProgrammeCollectionChange"
-SendNewsSubscriptionLevel%(playerID%,genre@,level@)="_bb_TTVGNetwork_SendNewsSubscriptionLevel"
-SendNews%(playerID%,news:TNews)="_bb_TTVGNetwork_SendNews"
-SendPlanNewsChange%(playerID%,newsBlock:TNewsBlock,add@=1)="_bb_TTVGNetwork_SendPlanNewsChange"
-GotPacket_Plan_NewsChange%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_Plan_NewsChange"
-GotPacket_NewsSubscriptionLevel%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_NewsSubscriptionLevel"
-GotPacket_SendNews%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_SendNews"
-GotPacket_ProgrammeCollectionChange%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_ProgrammeCollectionChange"
-GotPacket_ElevatorRouteChange%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_ElevatorRouteChange"
-GotPacket_ElevatorSynchronize%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_ElevatorSynchronize"
-GotPacket_StationChange%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_StationChange"
-GotPacket_Plan_AdChange%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_Plan_AdChange"
-GotPacket_Plan_ProgrammeChange%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_Plan_ProgrammeChange"
-GotPacket_GameReady%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_GameReady"
-GotPacket_SendContract%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_SendContract"
-GotPacket_SendProgramme%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_SendProgramme"
-GotPacket_PlayerPosition%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_PlayerPosition"
-GotPacket_PlayerDetails%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_PlayerDetails"
-GotPacket_PlayerIPs%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_PlayerIPs"
-GotPacket_Join%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_Join"
-GotPacket_AnnounceGame%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_AnnounceGame"
-GotPacket_ChatMessage%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_ChatMessage"
-GotPacket_SetSlot%(_IP%,_Port@@)="_bb_TTVGNetwork_GotPacket_SetSlot"
-SendState%()="_bb_TTVGNetwork_SendState"
-UpdateUDP%(fromNotConnectedPlayer%=0)="_bb_TTVGNetwork_UpdateUDP"
-ClearLastRecv%()="_bb_TTVGNetwork_ClearLastRecv"
-IsMsgNew@(id%,data%=0,_IP%,_Port@@)="_bb_TTVGNetwork_IsMsgNew"
-RemoveNetObj%(AckID%)="_bb_TTVGNetwork_RemoveNetObj"
-NetAck%(RecvID%,_IP%,_Port@@)="_bb_TTVGNetwork_NetAck"
-SendUDP%(i%=0)="_bb_TTVGNetwork_SendUDP"
-SendReliableUDP%(i%=0,retrytime%=200,MaxRetry%=-1,desc$=$"")="_bb_TTVGNetwork_SendReliableUDP"
-SendReliableUDPtoIP%(_IP%,_Port@@,retrytime%=200,MaxRetry%=-1,desc$=$"")="_bb_TTVGNetwork_SendReliableUDPtoIP"
-NetConnect%()="_bb_TTVGNetwork_NetConnect"
-NetDisconnect%(RealQuit@=1)="_bb_TTVGNetwork_NetDisconnect"
}="bb_TTVGNetwork"
TReliableUDP^brl.blitz.Object{
LastID%&=mem("_bb_TReliableUDP_LastID")
List:brl.linkedlist.TList&=mem:p("_bb_TReliableUDP_List")
.id%&
.SendID%&
.LastSent%&
.desc$&
.Retry%&
.MaxRetry%&
.content:brl.bank.TBank&
.targetIP%&
.targetPort@@&
.retrytime%&
-New%()="_bb_TReliableUDP_New"
+Create:TReliableUDP(SendID%,IP%,Port@@,content:brl.bank.TBank,retrytime%=200,MaxRetry%=-1,desc$=$"")="_bb_TReliableUDP_Create"
+GotAckPacket%(SendID%,fromIP%,fromPort@@)="_bb_TReliableUDP_GotAckPacket"
+ReSend%()="_bb_TReliableUDP_ReSend"
+DeletePacketsForIP%(_IP%,_Port@@)="_bb_TReliableUDP_DeletePacketsForIP"
+DeletePacketsWithCommand%(desc$)="_bb_TReliableUDP_DeletePacketsWithCommand"
}="bb_TReliableUDP"
NetObj^brl.blitz.Object{
.id%&
.SID%&
.T%&
.Retry%&
-New%()="_bb_NetObj_New"
+Create:NetObj(id%)="_bb_NetObj_Create"
-handle%()="_bb_NetObj_handle"
}="bb_NetObj"
PlannerToolTip:TTooltip&=mem:p("bb_PlannerToolTip")
Room_MovieAgency_GimmickTimer%&=mem("bb_Room_MovieAgency_GimmickTimer")
DrawnOnProgrammePlannerBG@&=mem:b("bb_DrawnOnProgrammePlannerBG")
part_array:Tparticle&[]&=mem:p("bb_part_array")
spawn_delay%&=mem("bb_spawn_delay")
pcount%&=mem("bb_pcount")
part_counter%&=mem("bb_part_counter")
plength%&=mem("bb_plength")
activeKI:KI&=mem:p("bb_activeKI")
Fader:TFader&=mem:p("bb_Fader")
PrepareScreenshot%&=mem("bb_PrepareScreenshot")
ArchiveProgrammeList:TgfxProgrammelist&=mem:p("bb_ArchiveProgrammeList")
PPprogrammeList:TgfxProgrammelist&=mem:p("bb_PPprogrammeList")
PPcontractList:TgfxContractlist&=mem:p("bb_PPcontractList")
Btn_newsplanner_up:TGUIImageButton&=mem:p("bb_Btn_newsplanner_up")
Btn_newsplanner_down:TGUIImageButton&=mem:p("bb_Btn_newsplanner_down")
gfx_building_skyscraper:TBigImage&=mem:p("bb_gfx_building_skyscraper")
SaveError:TError&=mem:p("bb_SaveError")
LoadError:TError&=mem:p("bb_LoadError")
ExitGame%&=mem("bb_ExitGame")
NewsAgency:TNewsAgency&=mem:p("bb_NewsAgency")
App:TApp&=mem:p("bb_App")
StationMap:TStationMap&=mem:p("bb_StationMap")
Interface:TInterface&=mem:p("bb_Interface")
Game:TGame&=mem:p("bb_Game")
Building:TBuilding&=mem:p("bb_Building")
Player:TPlayer&[]&=mem:p("bb_Player")
tempfigur:TFigures&=mem:p("bb_tempfigur")
figure_HausmeisterID%&=mem("bb_figure_HausmeisterID")
figure_Bote1ID%&=mem("bb_figure_Bote1ID")
figure_Bote2ID%&=mem("bb_figure_Bote2ID")
gfx_elevator_sign:brl.max2d.TImage&[]&=mem:p("bb_gfx_elevator_sign")
gfx_elevator_sign_dragged:brl.max2d.TImage&[]&=mem:p("bb_gfx_elevator_sign_dragged")
gfx_financials_barren:brl.max2d.TImage&[]&=mem:p("bb_gfx_financials_barren")
MenuPlayerNames:TGUIinput&[]&=mem:p("bb_MenuPlayerNames")
MenuChannelNames:TGUIinput&[]&=mem:p("bb_MenuChannelNames")
MenuFigureArrows:TGUIArrowButton&[]&=mem:p("bb_MenuFigureArrows")
MainMenuButton_Start:TGUIButton&=mem:p("bb_MainMenuButton_Start")
MainMenuButton_Network:TGUIButton&=mem:p("bb_MainMenuButton_Network")
MainMenuButton_Online:TGUIButton&=mem:p("bb_MainMenuButton_Online")
NetgameLobbyButton_Join:TGUIButton&=mem:p("bb_NetgameLobbyButton_Join")
NetgameLobbyButton_Create:TGUIButton&=mem:p("bb_NetgameLobbyButton_Create")
NetgameLobbyButton_Back:TGUIButton&=mem:p("bb_NetgameLobbyButton_Back")
NetgameLobby_gamelist:TGUIList&=mem:p("bb_NetgameLobby_gamelist")
GameSettingsBG:TGUIBackgroundBox&=mem:p("bb_GameSettingsBG")
GameSettingsOkButton_Announce:TGUIOkButton&=mem:p("bb_GameSettingsOkButton_Announce")
GameSettingsGameTitle:TGuiInput&=mem:p("bb_GameSettingsGameTitle")
GameSettingsButton_Start:TGUIButton&=mem:p("bb_GameSettingsButton_Start")
GameSettingsButton_Back:TGUIButton&=mem:p("bb_GameSettingsButton_Back")
GameSettings_Chat:TGUIChat&=mem:p("bb_GameSettings_Chat")
InGame_Chat:TGUIChat&=mem:p("bb_InGame_Chat")
Network:TTVGNetwork&=mem:p("bb_Network")
Database:TDatabase&=mem:p("bb_Database")
PlayerDetailsTimer%&=mem("bb_PlayerDetailsTimer")
MenuPreviewPicTimer%&=mem("bb_MenuPreviewPicTimer")
MenuPreviewPicTime%&=mem("bb_MenuPreviewPicTime")
MenuPreviewPic:TGW_Sprites&=mem:p("bb_MenuPreviewPic")
Betty:TBetty&=mem:p("bb_Betty")
LogoTargetY#&=mem:f("bb_LogoTargetY")
LogoCurrY#&=mem:f("bb_LogoCurrY")
Curves:TNumberCurve&=mem:p("bb_Curves")
DelayPossible%&=mem("bb_DelayPossible")
Init_Complete%&=mem("bb_Init_Complete")
